### ISSUE TITLE
Add formatting for disabled button state

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/ttkbootstrap#1]

**Comment by daniilS** [comment]
I feel like for some themes (flatly, lumen, cyborg), the grey-on-grey entry widgets would also be more suitable for the disabled state.

**Comment by israel-dryer** [comment]
possibly. But, I do like the contrast on the gray input vs. the white background though.  One simple and scalable solution might be to de-saturate the colors on all disabled widgets.

![image](https://user-images.githubusercontent.com/42584742/114255260-4a859a00-9982-11eb-89bc-d9455f76a14e.png)

**Comment by daniilS** [comment]
Yeah, I agree it does look nice, so I guess it's a trade-off between style and potential confusion as the colours do look very similar to the disables buttons in the bootstrap theme it came from. I don't mind much as I'm using the yeti in my current project.

Another scalable option for disabled widgets is to take the rgb average between each colour and the frame background colour: 
![image](https://user-images.githubusercontent.com/6144189/114286046-70c73a80-9a53-11eb-8264-0e73f326ccc0.png)

**Comment by israel-dryer** [comment]
Yeah true. I could also use a darker fg color in the input widgets. The reason I used the lighter shade was to mimic the bootstrap themes. But, I'm not necessarily married to it.

The saturation and lightness is hard to make consistently correct... I'm having some issues trying to keep the colors contrasted sufficiently to be legible, but also indicate clearly a disabled state. It might not be worth the extra effort. I'm tempted to just use the standard dim grey tone for disabled buttons & widgets. 

![image](https://user-images.githubusercontent.com/42584742/114287393-76f9ee80-9a34-11eb-9bcd-19d0072b8a18.png)

I really wish there was an easy way to add stippled, as that would be another nice option... but unfortunately, though the option is available in the  `Button.label` element options, I see no way to actually implement it.

**Comment by daniilS** [comment]
I'd support making the input text a little darker, the added contrast should make them a lot more readable. The grey tones work great (and wouldn't even need to differ between themes much, if at all), but if you decide you want to keep the difference between button colours in the disabled state, I think the fake transparency would be the easiest way to preserve contrast. Though I guess it would lose its effect if the widget is placed in a frame with its own background colour...

**Comment by israel-dryer** [comment]
I ended up adding a new set of colors for each theme: *inputbg*, *disabledfg*, *disabledbg*. This turned out well for most of the themes. There are a few that might need adjusted on the *inputfg* and *inputbg*.  However, all-in-all, this ended up being much easier than trying to do it programmatically, and with acceptable results I think. This creates more colors on the `ttkcreator` app, however. The color list is getting a bit long, and the shape of the app a bit unwieldy. But, I'll open another issue for that.

Let me know what you think of the disabled colors + the new input fg & bg colors.

**Comment by israel-dryer** [comment]
![image](https://user-images.githubusercontent.com/42584742/114338809-da157f00-9b21-11eb-955b-2fe3e5dcf0ad.png)

**Comment by israel-dryer** [comment]
![image](https://user-images.githubusercontent.com/42584742/114338917-11842b80-9b22-11eb-943e-b30313d57b0e.png)

**Comment by israel-dryer** [comment]
![image](https://user-images.githubusercontent.com/42584742/114339123-7ccdfd80-9b22-11eb-8e29-9f8e174414dc.png)

**Comment by israel-dryer** [comment]
![image](https://user-images.githubusercontent.com/42584742/114339201-a38c3400-9b22-11eb-9c33-7ab9646703f1.png)

**Comment by israel-dryer** [comment]
@daniilS, I had to make some tweaks to the color palette when adding the inputfg and disabled colors. The lighter inputfg DOES make the disabled state more clear, but it also results in a much brighter contrast vs. the more muted colors of the original, especially on dark themes.  As an example:

**original**
![cyborg](https://user-images.githubusercontent.com/42584742/114339927-6b85f080-9b24-11eb-81fc-cb0bf9497d80.png)
**new**
![image](https://user-images.githubusercontent.com/42584742/114339918-632db580-9b24-11eb-825a-962be0f82564.png)

**Comment by daniilS** [comment]
I agree that the muted look is a lot nicer than the bootswatch original. It might be better to leave the inputbg unchanged (it might not even need its own setting), and just darken the existing inputfg a little:
Original:
![lumen](https://user-images.githubusercontent.com/6144189/114374020-19bc8500-9b7b-11eb-93c6-86b90b89997f.png)
Darker inputfg:
![lumen](https://user-images.githubusercontent.com/6144189/114374346-71f38700-9b7b-11eb-828e-3af99282ccf0.png)
Original:
![flatly](https://user-images.githubusercontent.com/6144189/114374139-3a84da80-9b7b-11eb-841e-0bd88e1d1da6.png)
Darker inputfg:
![flatly](https://user-images.githubusercontent.com/6144189/114374165-3fe22500-9b7b-11eb-8f20-3dee188977ce.png)
Original:
![cyborg](https://user-images.githubusercontent.com/6144189/114374196-496b8d00-9b7b-11eb-94f9-57b9efa5ff20.png)
Darker inputfg:
![cyborg](https://user-images.githubusercontent.com/6144189/114374212-4d97aa80-9b7b-11eb-9068-6d85c52e0975.png)

**Comment by israel-dryer** [comment]
yeah, agreed. I simplified the color palette by removing disabled button colors. I merged *light* and *inputbg* into one *inputbg*. The disabled colors are modifications of the input colors. The end result is that I have the same number of colors as originally except that now I have inputbg instead of light, which I think makes more sense from a design perspective.

**Comment by israel-dryer** [comment]
I also reviewed all of the themes are darkened the *inputfg*

**Comment by daniilS** [comment]
I like the new colours! My only comment is that now there's no difference between disabled buttons, outline buttons, and entry-like widgets. What do you think of keeping disabled solid buttons as they are now, and for outline buttons and entry widgets, not changing the background at all when they get disabled, but setting both `bordercolor` and `foreground` to `(Colors.update_hsv(self.theme.colors.inputbg, vd=-0.2) if self.theme.type =='light' else
                       Colors.update_hsv(self.theme.colors.inputbg, vd=-0.3))` when they do?

**Comment by israel-dryer** [comment]
I like the idea with the outline buttons & outline menubuttons. I'm not sure about the entry widgets... let me think about that one. 

The secondary colors on some of these themes are pretty dim already for the outline button. But, I'm not too worried about that. It's available because it's in the color palette, but not necessarily useful on all occasions. For all other colors, the disabled state seems to work just fine. 

![image](https://user-images.githubusercontent.com/42584742/114448561-b5f98280-9ba1-11eb-83c3-6eecbc3b2516.png)
![image](https://user-images.githubusercontent.com/42584742/114448370-759a0480-9ba1-11eb-80bb-64801ed55eb3.png)

**Comment by israel-dryer** [comment]
ok. yeah, I think the entry looks good too with just the text muted. I'll make those changes to all input widgets.

![image](https://user-images.githubusercontent.com/42584742/114449255-8b5bf980-9ba2-11eb-95c0-f83327a8572e.png)
![image](https://user-images.githubusercontent.com/42584742/114449353-a3cc1400-9ba2-11eb-82b7-d52fc4aac780.png)

**Comment by daniilS** [comment]
Looks great! Agree about the issue with the outline buttons, but I think that's more of a reason not to use that colour as an outline button if it's so dim already, and the difference should still be clear when it's hovered over.

**Comment by israel-dryer** [comment]
Sounds good. I'll go ahead and close this issue then. Thanks for your help.
