### ISSUE TITLE
Entry with bootstyle='disabled' or bootstyle='readonly' , in some themes the foreground is highlighted more than the normal style.

### ISSUE THREAD

**Issue by antrrax** [israel-dryer/ttkbootstrap#103]
Watching the Entry with bootstyle='disabled' or bootstyle='readonly' , I noticed that in some themes the foreground color is not faded compared to the normal style color.
I think this could be improved, as as it is now, normal and disabled Entry are visually the same.

See a demo video below.
https://www.mediafire.com/file/q4s24rgld6euqi1/entry_disabled.mp4/file

these themes below are in bootstyle='disabled' mode or bootstyle='readonly' are foregrounded with black highlighted instead of grayed out:
(journal, litera, lumen, minty, sandstone, united, yeti)

-----
Other point. For Entry in bootstyle='disabled' and bootstyle='readonly' mode wouldn't it be better if the mouse cursor is 'arrow' to differentiate even more from a normal Entry? Because the 'xterm' cursor gives the feeling that something can be typed into this entry.

**Comment by israel-dryer** [comment]
@antrrax, this is good feedback. I'll take a look at the items above and see what I can do about the cursor on those states as well.

**Comment by israel-dryer** [comment]
@antrrax, unfortunately, there is no way to set the cursor via a style.  However.... [I recently added a Window class](https://ttkbootstrap.readthedocs.io/en/latest/api/window/window/) that combines a lot of commonly used settings and features (including the theme). And, I can use that class to create a class-level binding for all `Entry`, `Spinbox`, and `Combobox` widgets. This will effectively do what you are looking for.

proposed update to the `Window` class
```python
class Window(tkinter.Tk):
    ...

    def _apply_entry_type_class_binding(self):
        self.bind_class(
            className="TEntry", 
            sequence="<Configure>", 
            func=self._disabled_state_cursor,
            add="+"
        )
        self.bind_class(
            className="TSpinbox", 
            sequence="<Configure>", 
            func=self._disabled_state_cursor,
            add="+"
        )
        self.bind_class(
            className="TCombobox", 
            sequence="<Configure>", 
            func=self._disabled_state_cursor,
            add="+"
        )

    def _disabled_state_cursor(self, event):
        """Change the cursor of entry type widgets to 'arrow' if in a disabled
        or readonly state."""
        widget = self.nametowidget(event.widget)
        state = str(widget.cget('state'))
        if state in (DISABLED, READONLY):
            widget['cursor'] = 'arrow'
        else:
            widget['cursor'] = None
```
![XRFpyUD5ag](https://user-images.githubusercontent.com/42584742/147521701-91184d07-70e0-4689-8b7c-1f60cdb3c829.gif)

**Comment by antrrax** [comment]
@israel-dryer

Following this same reasoning, on buttons with bootstyle='link', the default mouse could be changed to 'hand1'

**Comment by israel-dryer** [comment]
@antrrax, unfortunately this won't be possible in the same way for link as this change cannot be done via style. I'm doing it with a widget class binding.

**Comment by israel-dryer** [comment]
Still need to fix read only and disable colors on some themes.

**Comment by israel-dryer** [comment]
I've change the disabled fg color so that it is a lot more muted - I'm using the bordercolor for the respective theme to set the disabled fg color. This was changed for Entry, Combobox, and Spinbox.

<img width="117" alt="image" src="https://user-images.githubusercontent.com/42584742/147907872-56e39dc6-a5e8-4ef9-be58-6fe6018ad4d9.png">
<img width="117" alt="image" src="https://user-images.githubusercontent.com/42584742/147907925-cbdec9e9-fe33-4825-a89b-5165136ed776.png">
