### ISSUE TITLE
Would it be possible to create a custom style for ttk.Menu ? Or Would it be possible for you to implement this in ttk.Menu?

### ISSUE THREAD

**Issue by antrrax** [israel-dryer/ttkbootstrap#105]
Would it be possible to create a custom style for ttk.Menu ? Or Would it be possible for you to implement this in ttk.Menu?

I currently use code similar to this one to change the style of a Menu:

```
self.menu_opt = ttk.Menu(self.btn_opt, tearoff = 0, font=('', 14), relief=FLAT)
self.menu_opt.configure(background='#000000', foreground='#ffffff', borderwidth=8)
```

I would like to do something like:

```
self.style = ttk.Style()
self.style.configure('header.TMenu', background='#000000', foreground='#ffffff', borderwidth=8)

self.menu_opt = ttk.Menu(self.btn_opt, tearoff = 0, font=('', 14), relief=FLAT)
self.configure(style='header.TMenu')
```
----------
Because if I change the theme dynamically tk resets the widget settings to the default theme.
I lose both the 'self.menu_opt.configure(...' information and the 'self.configure(style=header.'...
But in widgets that support styles I can reload the style in master by calling again:

`self.configure(style='header.TMenu')`

------

This is the initial Menu image (black background, white text and border 8)
self.menu_opt.configure(background='#000000', foreground='#ffffff', borderwidth=8)
<a href="https://ibb.co/mXVZVpj"><img src="https://i.ibb.co/2s1V1J9/01.png" alt="01" border="0"></a>

If I change the theme dynamically with this command:
`self.master.style.theme_use('cosmo')`

Here's how it looks after changing to any theme and then back to the initial theme.
See menu returns to default settings (white background, black text and border 1)
<a href="https://ibb.co/qn7GQmL"><img src="https://i.ibb.co/dcj9Yks/02.png" alt="02" border="0"></a>

**Comment by israel-dryer** [comment]
The Menu widget isn't natively theme-able, unfortunately; it's a legacy tkinter widget that I've set some default styles for to make it look ok in a themed environment. However, I recently made an update... I think in v1.2.0 where you can turn off the autostyle for the legacy tk widgets (which is what the menu is).

```python
self.menu_opt = ttk.Menu(self.btn_opt, tearoff = 0, font=('', 14), relief=FLAT, autostyle=False)
```
If you add the `autostyle` parameter to **False**, your custom style will be retained when the theme is updated.
