### ISSUE TITLE
Scrolled/Tableview not present in pip release

### ISSUE THREAD

**Issue by Ewind42** [israel-dryer/ttkbootstrap#116]
Hi, 

I have installed ttkbootstrap via pip, updated to version 1.2, pip fully updated on windows 10, python 3.10. 

The additions of 1.2 aren't installed through the pip package, neither scrolled.py nor tableview.py are present in the source of that version downloaded through pip. Hence, the use ttkbootstrap.scrolled fails, with a "module 'ttkbootstrap' has no attribute 'scrolled'" error. 

I am sorry if it's an obvious error that I missed. 
 
Thanks a lot.

**Comment by israel-dryer** [comment]
Hi, you are correct. I was planning on releasing it a few days ago, but wanted to clean some things up first. I'm hoping to release 1.3 this week, to include scrolling, tableview, and several other things.

**Comment by Ewind42** [comment]
Oh ok. I thought that the addition of 1.2 was  scrolled and tableview. Sorry for disturbance.

**Comment by israel-dryer** [comment]
No problem. Here's where you can check the changelog for future reference. https://ttkbootstrap.readthedocs.io/en/latest/changelog/

Unfortunately, those changes are showing up the documentation already, so that could be confusing.

**Comment by Ewind42** [comment]
Yes, because I'm to recreate a checklist with a scrolling bar , and was looking into the documentation on how to do it and stumbled upon the scrolled frame, that would have been perfect. 

Thanks a lot.

**Comment by israel-dryer** [comment]
@Ewind42, this has been published now.
https://github.com/israel-dryer/ttkbootstrap/releases/tag/v1.3.0

**Comment by Ewind42** [comment]
@israel-dryer 
Hello, 

Thanks a lot for the quick release. 
Just so you know, the behaviour of ScrolledFrame when using grid to place them iffy when the contents aren't initialised at the creation. F
Something like the code below results in a non usable frame, since the scrolling ends up being broken. You can't scroll down, only up, and the space scrolled through is blank and not rendering. 


```
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap.scrolled import ScrolledFrame


def add_values():
    for x in range(40):
        ttk.Checkbutton(sf, text=f"Checkbutton {x}").pack(anchor=W)
app = ttk.Window()
button =  ttk.Button(app, command = add_values)
button.grid(row= 0, column=0, sticky="nesw")

sf = ScrolledFrame(app, autohide=True)
sf.grid(row =1, column = 0, sticky="nesw")

app.mainloop()    
``` 

   

I have uploaded a screen. 
![image](https://user-images.githubusercontent.com/12500486/148073708-9b193a6b-998b-4000-bedf-dce2c34d200c.png)

There is a workaround that works : you can initialise the ScrolledFrame by filling it with more items than in your final usecase, as long as you reset it once the mainloop is running. If you reset it before the mainloop is running you end up in the same case as before. If you have less item in your initialisation than in the end use case, you end up with 

```
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap.scrolled import ScrolledFrame

def init_list(sf):
    global list_buttons
    for x in range(80):
        list_buttons.append(ttk.Checkbutton(sf, text=f"Click the button to fill the list"))
        list_buttons[-1].pack(anchor=W)

def add_values():
    reset()
    global list_buttons
    for x in range(40):
        list_buttons.append(ttk.Checkbutton(sf, text=f"Checkbutton {x}"))
        list_buttons[-1].pack(anchor=W)
def  reset(): 
    global list_buttons
    for i in range(len(list_buttons)):
        k = list_buttons.pop()
        k.destroy()

app = ttk.Window()

button =  ttk.Button(app, command = add_values)
button.grid(row= 0, column=0, sticky="nesw")
list_buttons = []
sf = ScrolledFrame(app, autohide=True)
sf.grid(row =1, column = 0, sticky="nesw")
init_list(sf)

app.mainloop()     
```   

The code is ugly due to the use of global variable, but it works. 
If you need more information, I can  try more things. Sorry if my use case of grid() is just bad practices (I'm just learning Tkinter). 
 
I love the new feature. Thanks a lot.
