### ISSUE TITLE
Entry adds 1 to typed page number when in limit

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/ttkbootstrap#130]
I don't know if I should open another issue, or post it here

I'm testing this new version of Widget.

When the typed page is smaller or larger than the limit, it is now correct. But when the typed page is in the limit, it adds 1 to the typed page number.

-----

Striped lines are not being applied (bg and fg were not passed to the striped attribute). With this change below, it is possible to apply the striped lines:

```
    def apply_table_stripes(self, stripecolor):
        if len(stripecolor) == 2:
            self._stripecolor = stripecolor
            bg, fg = stripecolor
            kw = {}
            if bg is None:
                kw["background"] = colors.active
            else:
                kw["background"] = bg

            if fg is None:
                kw["foreground"] = colors.inputfg
            else:
                kw["foreground"] = fg

            self.view.tag_configure("striped", **kw)
```
Needed to add this:
```
            else:
               kw["background"] = bg
```
and that: 
```
            else:
                kw["foreground"] = fg
```

_Originally posted by @antrrax in https://github.com/israel-dryer/ttkbootstrap/issues/123#issuecomment-1008096189_

**Comment by antrrax** [comment]
Another problem I encountered.
When is on the last page:
- select all lines,
- deletes all lines from the last page

the Index changes to the previous page, but the treeview is blank

the expected is to load the data from this previous page

**Comment by antrrax** [comment]
when sorting columns, it does not select the first row.

In my case I found it more practical to add this at the end of the 'load_table_data' method:
`self._select_first_visible_item()`

Whenever you load or reload data, you already select the first item

----------------

However, even with the first line selected, it does not respond to the mouse up and down arrows. Need to click on a row to use the to navigate.
