### ISSUE TITLE
Larger button text and tab text size

### ISSUE THREAD

**Issue by andrewguy** [israel-dryer/ttkbootstrap#132]
Is it possible to increase the `ttk.Button` text size and `ttk.Notebook` tab size while still using the standard `ttkbootstrap` styling?

It seems like it should be an easy thing to achieve, but I can't for the life of me figure out how.

Many thanks,
Andrew

**Comment by israel-dryer** [comment]
yes, you can configure the underlying ttk style.

Here is the starting example of a button with a _success_ bootstyle applied.

```python
import ttkbootstrap as ttk

app = ttk.Window()

btn = ttk.Button(text='Push Button', bootstyle='success')
btn.pack(padx=10, pady=10)

app.mainloop()
```
<img width="125" alt="python_BqERfULq7w" src="https://user-images.githubusercontent.com/42584742/148953933-70486d50-257e-4d08-867d-cadc82bec766.png">

To find the ttk style used by the widget:
```python
>>> btn.cget('style')
'success.TButton'
```

Change the font size on all buttons with the widget style 'success.TButton'
```python
# use 'None' for the font name if you only want to change the size
app.style.configure('success.TButton', font=(None, 25))
```
<img width="161" alt="python_pdI4QTSHxP" src="https://user-images.githubusercontent.com/42584742/148954594-6d504a57-29dd-43bd-beeb-bf6dafe4a66a.png">

Change the font size on ONLY this button using a subclassed style
```python
# create the new style
app.style.configure('my.success.TButton', font=(None, 25))

# add the custom style to the button
btn.configure(style='my.success.TButton')
```

Change the font size on ALL buttons
```python
app.style.configure('TButton', font=(None, 25))
```

**Comment by israel-dryer** [comment]
@andrewguy, the tab on the notebook is similar... whatever style you are using on the notebook, there is another 'Tab' style. For example, using a default style, I would update the "TNotebook.Tab" font. Using an _info_ bootstyle with a ttkstyle of "info.TNotebook" I would update the "info.TNotebook.Tab" style.

```python
app.style.configure('info.TNotebook.Tab', font=(None, 25)
```

BEFORE
<img width="114" alt="python_dkMzncI1aJ" src="https://user-images.githubusercontent.com/42584742/148958182-7a6bce18-d48e-474c-b747-38a34d0a3032.png">

AFTER
<img width="160" alt="python_gCxce2iouj" src="https://user-images.githubusercontent.com/42584742/148958253-99adc3a4-64c5-49c1-9116-8c06759dc06c.png">

**Comment by antrrax** [comment]
> Here is the starting example of a button with a _success_ bootstyle applied.

This answer could be part of the 'Getting started' documentation a new page: "customizing themes"
https://ttkbootstrap.readthedocs.io/en/latest/gettingstarted/tutorial/

**Comment by israel-dryer** [comment]
> > Here is the starting example of a button with a _success_ bootstyle applied.
> 
> This answer could be part of the 'Getting started' documentation a new page: "customizing styles" https://ttkbootstrap.readthedocs.io/en/latest/gettingstarted/tutorial/

Good idea!

**Comment by antrrax** [comment]
I'll take advantage of this topic and ask another question.
When I have a custom style and I change the theme at runtime, would it be possible to reload all the custom styles along with the theme change, or do I have to reload each style manually?

I have this theme:
```
self.style = ttk.Style()
self.style.configure('pwdimg.TButton', padding=[5,0])
self.btn.configure(style='pwdimg.TButton')
```

currently when making the change:
`self.master.style.theme_use(user_theme)`

need to reapply with every theme change:
`style.configure('pwdimg.TButton', padding=[5,0])`

**Comment by israel-dryer** [comment]
> I'll take advantage of this topic and ask another question. When I have a custom style and I change the theme at runtime, would it be possible to reload all the custom styles along with the theme change, or do I have to reload each style manually?
> 
> I have this style:
> 
> ```
> self.style = ttk.Style()
> self.style.configure('pwdimg.TButton', padding=[5,0])
> self.btn.configure(style='pwdimg.TButton')
> ```
> 
> currently when making the change: `self.master.style.theme_use(user_theme)`
> 
> need to reapply with every theme change: `style.configure('pwdimg.TButton', padding=[5,0])`

Yes, there is a way to do this with vanilla ttk using the virtual event "\<\<ThemeChanged\>\>"

```python
# add all your custom style to a method that accepts an event parameter
# I'm also assuming you are adding this to the class, otherwise self is not required
def custom_styles(self, event):
    """Update custom styles when the theme is updated"""
    self.style.configure('pwdimg.TButton', padding=[5,0])

# register the method with theme changed event
self.bind("<<ThemeChanged>>, custom_styles, add="+")
```

**Comment by andrewguy** [comment]
Thanks @israel-dryer for the super quick and very helpful response. This is great!

I'll close this issue as you've answered my question, but I also want to say a huge thanks for the development of the `ttkbootstrap` tool. Really excellent work.

**Comment by israel-dryer** [comment]
> Thanks @israel-dryer for the super quick and very helpful response. This is great!
> 
> I'll close this issue as you've answered my question, but I also want to say a huge thanks for the development of the `ttkbootstrap` tool. Really excellent work.

Thanks, appreciate the feedback.

**Comment by antrrax** [comment]
> Yes, there is a way to do this with vanilla ttk using the virtual event "<<ThemeChanged>>"

In 'Getting started' it would also be interesting to put with this answer, the correct way to insert a theme, custom styles and change the theme at runtime.
