### ISSUE TITLE
Add this theme

### ISSUE THREAD

**Issue by NewbieXvwu** [israel-dryer/ttkbootstrap#142]
https://github.com/rdbende/Sun-Valley-ttk-theme
Maybe my request is a little silly, but I think your program is easy to switch themes.Or you can teach me how to use it with your program.Thank you!

**Comment by israel-dryer** [comment]
Sorry, this theme would not be compatible with ttkbootstrap. See my comments in your previous thread.

**Comment by israel-dryer** [comment]
This is similar to the other issue you posted, so I'll close this one.
