### ISSUE TITLE
ttk.Checkbutton OSError 

### ISSUE THREAD

**Issue by aatambo** [israel-dryer/ttkbootstrap#143]
Run this code and you will find an OSError: cannot open resource

```bash
import tkinter as tk
import ttkbootstrap as ttk

root = tk.Tk()

c1 = ttk.Checkbutton(root, text='music')
c1.grid ()

root.mainloop()
```

N/B : If i add bootstyle='success-round-toggle' it works
What might be wrong? Why does it not work without a bootstyle configuration?
I'm using manjaro linux incase it might be helpful.

**Comment by israel-dryer** [comment]
Can you paste the exact error you are getting?

Can you give me a few more pieces of information:
- [ ] python version
- [ ] ttkbootstrap version

Do you get the same error if you do not import tkinter and instead used ttk.Window to create the root?

**Comment by aatambo** [comment]
python version 3.9.7
ttkbootstrap 1.5.0

I get the same errot still with ttk.window()
```bash
import ttkbootstrap as ttk
from ttkbootstrap.constants import *

root = ttk.Window()
root.geometry('800x500')


c = ttk.Checkbutton(root)
c.grid()

root.mainloop()
```

This is the error:

Traceback (most recent call last):
  File "/home/dev-reflex/Desktop/Laboratory/zzz.py", line 9, in <module>
    c = ttk.Checkbutton(root)
  File "/home/dev-reflex/.virtualenvs/tK/lib/python3.9/site-packages/ttkbootstrap/style.py", line 4825, in __init__
    ttkstyle = Bootstyle.update_ttk_widget_style(
  File "/home/dev-reflex/.virtualenvs/tK/lib/python3.9/site-packages/ttkbootstrap/style.py", line 4911, in update_ttk_widget_style
    builder_method(builder, widget_color)
  File "/home/dev-reflex/.virtualenvs/tK/lib/python3.9/site-packages/ttkbootstrap/style.py", line 3983, in create_checkbutton_style
    images = self.create_checkbutton_assets(colorname)
  File "/home/dev-reflex/.virtualenvs/tK/lib/python3.9/site-packages/ttkbootstrap/style.py", line 4053, in create_checkbutton_assets
    fnt = ImageFont.truetype("FreeSerif.ttf", 130)
  File "/home/dev-reflex/.virtualenvs/tK/lib/python3.9/site-packages/PIL/ImageFont.py", line 844, in truetype
    return freetype(font)
  File "/home/dev-reflex/.virtualenvs/tK/lib/python3.9/site-packages/PIL/ImageFont.py", line 841, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/dev-reflex/.virtualenvs/tK/lib/python3.9/site-packages/PIL/ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by israel-dryer** [comment]
Here is what I'm getting with other tests >>

Windows 11:

<img width="298" alt="Code_XYzgHgx7R3" src="https://user-images.githubusercontent.com/42584742/149782855-2a5cbe2e-851c-4155-8cb3-0d31754bd310.png">

Raspberry Pi OS:

<img width="291" alt="mstsc_z9rYznrAun" src="https://user-images.githubusercontent.com/42584742/149783246-65d1adbd-56d5-4f76-acc6-96f2ac64f77c.png">

Linux Ubuntu via replit.it

<img width="486" alt="msedge_UcRrhhbY1k" src="https://user-images.githubusercontent.com/42584742/149785176-70633fb1-c426-46d2-b535-4da8df028b8c.png">

**Comment by israel-dryer** [comment]
@aatambo, can you show the image of it working with the bootstyle? I'm confused why it would work at all with that error message.

**Comment by aatambo** [comment]
Does that mean it is either an Os related issue or python version?

**Comment by israel-dryer** [comment]
> Does that mean it is either an Os related issue or python version?

I'm not sure. From the error, it appears that it is having trouble finding the FreeSerif font, but that wouldn't make sense if you say it is working with a bootstyle. I'm going to download the OS and try it out. I'm curious about it anyway. I'll see if I can get the same error to show up. Might be a day or so as I have to work.

**Comment by aatambo** [comment]
with bootstyle
![with_bootstyle](https://user-images.githubusercontent.com/97674615/149786886-5c0da9fe-1fee-4b7a-8450-8088a4cea785.png)

without bootstyle
![without_bootstyle](https://user-images.githubusercontent.com/97674615/149786967-bd92e53a-1922-446a-86a4-154cff1553e3.png)

**Comment by israel-dryer** [comment]
ok, for whatever reason, the FreeSerif font is not installed in that distribution of Manjaro. Perhaps it's a minimal install version? The reason that the round-toggle works is because it does not use a font to render the button. The regular checkbox draws a checkmark using the FreeSerif font (on Linux) onto an image which displays in the button.

In the short term, you can fix by installing the FreeSerif font. I'm not familiar enough with Arch Linux to know how to do that. In the meantime, I'll look into adding another font check (perhaps the Noto family) so that it works with this distribution out-of-the-box.

**Comment by aatambo** [comment]
Okay thanks for your good work with ttkbootstrap.
Shall I close the issue now?

**Comment by israel-dryer** [comment]
You can leave it open until I resolve the font issue with that OS

**Comment by israel-dryer** [comment]
It's not my favorite choice, but I think I can make it work by adding the fallback font of DejaVuSans.ttf

<img width="463" alt="VirtualBoxVM_sCPdOpzgxr" src="https://user-images.githubusercontent.com/42584742/149870777-871c679c-6527-4c91-9c4c-70ddb52707eb.png">

**Comment by israel-dryer** [comment]
I was able to test this fix successfully on a Monjaro installation with version 1.5.1 using the new fallback font.

**Comment by aatambo** [comment]
Cool thanks
