### ISSUE TITLE
Check Button's Third State

### ISSUE THREAD

**Issue by NewbieXvwu** [israel-dryer/ttkbootstrap#145]
![image](https://user-images.githubusercontent.com/87637612/150448779-27718edf-6746-446e-a172-9d387146484d.png)
I don't think I need to say more.

**Comment by israel-dryer** [comment]
This is on the way

<img width="233" alt="python_BG5F9MA8KE" src="https://user-images.githubusercontent.com/42584742/153091841-d3837a43-48bf-4a26-a4cd-68798a70b143.png">
