### ISSUE TITLE
AttributeError: module 'calendar' has no attribute '_prevmonth'

### ISSUE THREAD

**Issue by funchan24** [israel-dryer/ttkbootstrap#150]
when i use ttkbootstrap's widget DateEntry and python standand library datetime.datetime at the same time, i got a AttributeError: module 'calendar' has no attribute '_prevmonth' (the '_nextmonth' ditto). change '_prevmonth' to 'prevmonth', '_nextmonth' to 'nextmonth' will avoid the error.

**Comment by israel-dryer** [comment]
can you post an example of the code you are using. Also, what OS are you using? And which version of ttkbootstrap?

**Comment by funchan24** [comment]
Windows 11 & Python 3.7.6 32bit & ttkbootstrap 1.51
My code:
`#!/usr/bin/env/python3
# -*- coding:utf-8 -*-

import functools
from threading import Thread
from tkinter import Misc
from typing import List, Tuple
from datetime import datetime

from ttkbootstrap import *
from ttkbootstrap.constants import *


class GUI(Window):

    @classmethod
    def multi_thread(cls, func):

        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            thread = Thread(target=func, args=args, kwargs=kwargs)
            thread.setDaemon(True)
            thread.start()

        return wrapper

    def __init__(self,
                 title="ttkbootstrap",
                 themename="litera",
                 iconphoto=None,
                 size=None,
                 position=None,
                 minsize=None,
                 maxsize=None,
                 resizable=None,
                 hdpi=True,
                 scaling=None,
                 transient=None,
                 overrideredirect=False,
                 alpha=1,
                 icon_path=None,
                 base_size=10):

        super().__init__(title=title,
                         themename=themename,
                         iconphoto=iconphoto,
                         size=size,
                         position=position,
                         minsize=minsize,
                         maxsize=maxsize,
                         resizable=resizable,
                         hdpi=hdpi,
                         scaling=scaling,
                         transient=transient,
                         overrideredirect=overrideredirect,
                         alpha=alpha)

        self.base_size = base_size
        self.add_widget()
        self.center_horizontally(self)

        self.icon_path = icon_path
        self.iconbitmap(self.icon_path)

        self.before_work()

        # self.bind('<Return>', self._start_work)
        self.protocol('WM_DELETE_WINDOW', self.after_work)

    def add_widget(self):
        """
        "-": means columnspan
        "/": means a blank Label
        """
        widgets_list = [[None] * 9 for _ in range(9)]
        for i in range(9):
            for j in range(9):
                if i >= j:
                    widgets_list[i][j] = Label(
                        self,
                        text=f'{j+1}*{i+1}={(i+1)*(j+1)}',
                        anchor=CENTER,
                        bootstyle=(SUCCESS, INVERSE))
                else:
                    widgets_list[i][j] = '/'

        self.grid_widget(widgets_list, self, self.base_size)

    def grid_widget(self,
                    widgets_list: List[List[Tuple[Misc, str]]],
                    master: Misc,
                    padding: int,
                    anchor: ANCHOR = CENTER):
        master.grid_anchor(anchor)

        max_column = len(widgets_list[0])
        assert all([len(widgets) == max_column for widgets in widgets_list
                    ]), 'the elements of each row are not equal'

        for row, widgets in enumerate(widgets_list):
            for column, widget in enumerate(widgets):
                if widget == '-':
                    pass

                else:
                    columnspan = 1
                    for i in range(column + 1, max_column):
                        if widgets[i] == '-':
                            columnspan += 1
                        else:
                            break

                    if widget == '/':
                        widget = Label(master)

                    try:
                        widget.grid(row=row,
                                    column=column,
                                    columnspan=columnspan,
                                    padx=padding // 2,
                                    pady=padding,
                                    ipadx=padding // 2,
                                    ipady=padding // 2,
                                    sticky=NSEW)
                    except AttributeError:
                        raise AttributeError(
                            f'''self.widgets_list can only contain "widget", "-" and "/", got a "{widget}".'''
                        )

    def center_horizontally(self, window: Tuple[Window, Toplevel]) -> None:
        window.withdraw()
        window.update()
        w_width = window.winfo_width()
        w_height = window.winfo_height()
        s_width = self.winfo_screenwidth()
        s_height = self.winfo_screenheight()
        xpos = (s_width - w_width) // 2
        ypos = int((s_height - w_height) * 0.382)
        window.geometry(f'+{xpos}+{ypos}')
        window.deiconify()

    def before_work(self):
        pass

    def start_work(self):
        pass

    def _start_word(self, event):
        return self.start_work()

    def after_work(self):
        self.destroy()


class App(GUI):

    def __init__(self,
                 title="ttkbootstrap",
                 themename="litera",
                 iconphoto=None,
                 size=None,
                 position=None,
                 minsize=None,
                 maxsize=None,
                 resizable=None,
                 hdpi=True,
                 scaling=None,
                 transient=None,
                 overrideredirect=False,
                 alpha=1,
                 icon_path=None,
                 base_size=10):
        super().__init__(title, themename, iconphoto, size, position, minsize,
                         maxsize, resizable, hdpi, scaling, transient,
                         overrideredirect, alpha, icon_path, base_size)

    def add_widget(self):
        self.widgets_list = [[DateEntry(self)]]
        self.grid_widget(self.widgets_list, self, 0)

    def start_work(self):
        date: datetime = self.widgets_list[0][0]._startdate
        print(date)


if __name__ == '__main__':
    app = App()
    app.mainloop()
`

<img width="1280" alt="8112f3db8d4bf9336d433fb9e921163" src="https://user-images.githubusercontent.com/42088233/150668186-fef4918f-07ce-4369-a02e-d76703efef09.png">

**Comment by israel-dryer** [comment]
Ok. That's strange. I'm unwisely using a private method in the python calendar module. So, likely it is not available in Python 3.7, which is why it's causing this issue. No worries, it is a simple method that I can just add into the class itself. Thanks for pointing this out.

**Comment by funchan24** [comment]
thanks for your great work!
