### ISSUE TITLE
Tkinter and Ubuntu/Linux: When exiting the program the clipboard is erased. All Widgets with copy function

### ISSUE THREAD

**Issue by antrrax** [israel-dryer/ttkbootstrap#167]
There is a problem with the tkinter clipboard handler on Ubuntu (I don't know if it happens with other distros), but any data copied to the clipboard is lost after the Tkinter program is closed.

https://stackoverflow.com/questions/46178950/tk-only-copies-to-clipboard-if-paste-is-used-before-program-exits

-------------
Here for me(Linux Mint) this function solves the problem, but it needs the external module `pyperclip`

In ttkbootstrap's Api/Widgets/Dialogs, I would need to attach this function to all widgets with copy function, or create new widgets already with this functionality built in.

```
import pyperclip

for sequence in ['<Control-c>', '<Control-C>']:
    self.entry.bind(
        sequence=sequence,
        func=self.on_copy_to_clibboard
    ) 

def on_copy_to_clibboard(self, event):
    if event.widget.select_present():
        self.clipboard_clear()
        self.update()
        pyperclip.copy(self.selection_get())
    return 'break'
```

**Comment by israel-dryer** [comment]
This issue duplicates the effort from https://github.com/israel-dryer/ttkbootstrap/issues/115

I'm not necessarily opposed to the idea, but I'd like to explore any alternatives that don't require additional dependencies just to fix a single tkinter bug.
