### ISSUE TITLE
Add stepsize parameter to Meter class

### ISSUE THREAD

**Issue by FinalSh4re** [israel-dryer/ttkbootstrap#170]
Hi there!

I previously implemented some (rather small) interactive dials (meters) for one of my applications. I found that especially for smaller sizes having a step size of 1 becomes extremely fiddly. The problem gets worse the bigger the max value is.
For my use case I was perfectly happy to have less precision but a much better user experience due to a larger step size.
Thus I though it might be useful to add a step size parameter to the Meter constructor (defaulting to 1 for backwards compatibility).

I ended up implementing this rather straightforwardly, not sure if this is the best method (or perhaps there is already a way to do this which I missed?):

```py
def _on_dial_interact(self, e):
    """Callback for mouse drag motion on meter indicator"""
    dx = e.x - self._metersize // 2
    dy = e.y - self._metersize // 2
    rads = math.atan2(dy, dx)
    degs = math.degrees(rads)

    if degs > self._arcoffset:
        factor = degs - self._arcoffset
    else:
        factor = 360 + degs - self._arcoffset

    # clamp the value between 0 and `amounttotal`
    amounttotal = self.amounttotalvar.get()
    
    # CHANGE HERE:
    amountused = self.step_size * round((amounttotal / self._arcrange * factor) / self.step_size)

    if amountused < 0:
        self.amountusedvar.set(0)
    elif amountused > amounttotal:
        self.amountusedvar.set(amounttotal)
    else:
        self.amountusedvar.set(amountused)
```

Keep up the good work!
Thank you!

**Comment by israel-dryer** [comment]
I think this parameter is a good suggestion. I'll add it to the development plan.

**Comment by israel-dryer** [comment]
@FinalSh4re, I just pushed this change, and also made an adjustment with image rendering that will significantly improve the performance while interacting with the mouse. The current version was a little sluggish because the initial image size was too large.
