### ISSUE TITLE
Can't get translations to work. 

### ISSUE THREAD

**Issue by dmalves** [israel-dryer/ttkbootstrap#171]
Hi,

I've got the latest ttkbootstrap from github today:

pip3 install git+https://github.com/israel-dryer/ttkbootstrap

then I cloned the repository:

git clone https://github.com/israel-dryer/ttkbootstrap

All examples work, but the translations. I tried the tests, and I could not get tableview or any dialog to be translated. I am using ubuntu linux:

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

Is there any specific command I need to choose the language? How do I know if ttkbootstrap is loading the correct the translation file? In my case it should be 'pt_br'.

EDIT: tried on python3.8.4

Thanks for your time.

**Comment by israel-dryer** [comment]
What value do you get if you run the `MessageCatalog.locale()` command?

**Comment by dmalves** [comment]
> What value do you get if you run the `MessageCatalog.locale()` command?

import ttkbootstrap as ttk
from ttkbootstrap.dialogs import Querybox, Messagebox
from ttkbootstrap.icons import Icon
# import tkinter as tk

from ttkbootstrap.localization import MessageCatalog
from ttkbootstrap import localization
localization.initialize_localities()

MessageCatalog.locale('pt_br')

Messagebox.yesnocancel("Messagebox.yesnocancel")


print("My locale:", MessageCatalog.locale())

---------------- console output after pressing "yes" ---------
My locale: pt_br
---------------- screen output ----------------------
![image](https://user-images.githubusercontent.com/5115787/152054333-365e6260-409f-4c2f-9fda-f14aeec7282e.png)

**Comment by dmalves** [comment]
If I remove: MessageCatalog.locale('pt_br')

I still get "My locale: pt_br"

**Comment by israel-dryer** [comment]
What locale is returned from the MessageCatalog.locale() method with no parameters. I'm wondering what native locale is recognized by tkinter.

**Comment by antrrax** [comment]
Take the following test.
download the repository zip file
https://codeload.github.com/israel-dryer/ttkbootstrap/zip/refs/heads/master

extract the contents of the zip file folder
/ttkbootstrap-master/src/ttkbootstrap/

to the python modules folder. In my case python 3.8
/home/YOUR_USER_NAME/.local/lib/python3.8/site-packages/ttkbootstrap/

See if the translation has been applied

-------------------

There seems to be a problem installing via pip
---------
See my test:
I deleted the folder 'ttkbootstrap' and 'ttkbootstrap-1.5.1.dist-info' in the directory:
/home/YOUR_USER_NAME/.local/lib/python3.8/site-packages
and I installed it via pip:
pip3 install git+https://github.com/israel-dryer/ttkbootstrap
see the result of your code, did not apply the translation:
![ingles](https://user-images.githubusercontent.com/24946480/152060795-baea7fa7-c87a-47fd-9234-5641bfb69cbc.png)

-----

To fix I downloaded the zip file
https://codeload.github.com/israel-dryer/ttkbootstrap/zip/refs/heads/master

and put the contents of the folder:
/ttkbootstrap-master/src/ttkbootstrap/
in the directory:
/home/YOUR_USER_NAME/.local/lib/python3.8/site-packages/ttkbootstrap/

see the result of your code, here applied the translation:
![pt](https://user-images.githubusercontent.com/24946480/152060816-90618a28-7b84-41e6-b53f-a774e2f300bf.png)

**Comment by israel-dryer** [comment]
I wonder if it's using the cached version of ttkbootstrap on the local machine?

**Comment by antrrax** [comment]
See the files downloaded and installed via pip (ttkbootstrap-1.5.1).
`pip3 install git+https://github.com/israel-dryer/ttkbootstrap`


There is no **msgs** folder, so the translation was not applied.
[ttkbootstrap_via_pip.zip](https://github.com/israel-dryer/ttkbootstrap/files/7982514/ttkbootstrap_via_pip.zip)

**Comment by israel-dryer** [comment]
@antrrax, @dmalves, you should get the msg files now when installing via github.

**Comment by antrrax** [comment]
I tested it here

via
`pip3 install git+https://github.com/israel-dryer/ttkbootstrap`

Successfully installed **ttkbootstrap-1.5.1.1**

**It worked as expected** - new version with translated text and colorchooser widget

------------

via:
`pip install ttkbootstrap`
Successfully installed **ttkbootstrap-1.5.1**
Old version - no translation and no colorchoser

**Comment by dmalves** [comment]
> @antrrax, @dmalves, you should get the msg files now when installing via github.
I installed the latest version using: 

pip3 install git+https://github.com/israel-dryer/ttkbootstrap

Translation is working (pt_br.msg is present) on python 3.8.10 as shown bellow

![image](https://user-images.githubusercontent.com/5115787/152212063-2d866cd2-e439-4f54-a9ae-bc32eeb78c1c.png)

I couldn't get it to work on python 3.9.0, but the reason is another bug:
https://github.com/israel-dryer/ttkbootstrap/issues/172
