### ISSUE TITLE
_get_default_root and some tkinter versions

### ISSUE THREAD

**Issue by dmalves** [israel-dryer/ttkbootstrap#172]
Hi,
_get_default_root  on the file ttkbootstrap/src/ttkbootstrap/localization/__init__.py /
is giving error on python3.9.0. It works fine on python3.8.4. It looks like _get_default_root is not present on python3.9.0. 

The line (14) that gives the error on  ttkbootstrap/src/ttkbootstrap/localization/__init__.py /:

from tkinter import _get_default_root as default_root

No _get_default_root on python3.9.0:
https://github.com/python/cpython/blob/v3.9.0/Lib/tkinter/__init__.py

But, _get_default_root comes back on python3.9.2:
https://github.com/python/cpython/blob/v3.9.2/Lib/tkinter/__init__.py#L291

I hope it helps clarify the error on _get_default_root.

Thanks for your time.

**Comment by israel-dryer** [comment]
Strange. It looks like both contain the default root variable. It should be easy enough to just create my own get_default_root method to get around this.

**Comment by dmalves** [comment]
> Strange. It looks like both contain the default root variable. It should be easy enough to just create my own get_default_root method to get around this.

On python 3.8.10:
![image](https://user-images.githubusercontent.com/5115787/152055030-84c1ef6b-eb31-4d3e-b862-8236e20fb0fa.png)

On python 3.9.0: no _get_default_root
![image](https://user-images.githubusercontent.com/5115787/152055261-b2ae0584-7464-4665-bb1d-910749ba541f.png)

On the links from python source code on my first post the same thing. My path to understand this was, first check on the interpreters on my machine, and then look on python source code.

**Comment by israel-dryer** [comment]
@dmalves, would you be able to test pip install this branch on the Python version that did not work, and let me know if it works.

```
pip install git+https://github.com/israel-dryer/ttkbootstrap.git@make-default-root-function-part-of-window-module
```

**Comment by dmalves** [comment]
> ```
> pip install git+https://github.com/israel-dryer/ttkbootstrap.git@make-default-root-function-part-of-window-module
> ```

I tested on python 3.9.0 (the offending version) and it is working perfectly. No _get_default_root bug and no missing translation files bug.

Thanks for answering so fast.
