### ISSUE TITLE
ScrolledFrame seems to be unscrollable in ttkbootstrap 1.5.1

### ISSUE THREAD

**Issue by lolghuiy4tgfyu4th7tvtg** [israel-dryer/ttkbootstrap#173]
When upgrading to ttkbootstrap 1.5.1, I found an issue with one of my apps. It uses buttons generated by 'for loops' to display options, and puts them in a ScrolledFrame. Anyways, for whatever reason in ttkbootstrap 1.5.1, the frame seems to have a scrollbar but it's unscrollable. Here's some gifs to see what I am talking about

1.5.0: 
![Tqw78xpu5S](https://user-images.githubusercontent.com/78936316/152058259-01e7d3ab-60d2-4b5f-a9f3-ec90c2755ae3.gif)

1.5.1: 
![sC9YNRjIOD](https://user-images.githubusercontent.com/78936316/152058173-8511613e-6a42-4807-a31e-9fec86cf64e8.gif)

Tested on Windows 10 with Python 3.10

**Comment by israel-dryer** [comment]
I'm going to combined this with #169 as I think they are related.
