### ISSUE TITLE
Wrong window positioning on dual monitor setup

### ISSUE THREAD

**Issue by FinalSh4re** [israel-dryer/ttkbootstrap#183]
I was notified by a user of mine that they're experiencing dialog windows opening in the middle of their dual screen setup. I don't have access to a second monitor at the moment so I can't confirm this myself, however a quick search returned `winfo_screenwidth()` in the `Dialog` base class' `_locate()` method as a likely culprit (see [this SO post](https://stackoverflow.com/questions/30312875/tkinter-winfo-screenwidth-when-used-with-dual-monitors)).

**Comment by israel-dryer** [comment]
> I was notified by a user of mine that they're experiencing dialog windows opening in the middle of their dual screen setup. I don't have access to a second monitor at the moment so I can't confirm this myself, however a quick search returned `winfo_screenwidth()` in the `Dialog` base class' `_locate()` method as a likely culprit (see [this SO post](https://stackoverflow.com/questions/30312875/tkinter-winfo-screenwidth-when-used-with-dual-monitors)).

Do you know if your user was using Windows, Mac, or Linux?

**Comment by FinalSh4re** [comment]
They are on Windows.

**Comment by israel-dryer** [comment]
> They are on Windows.

Ok. Same here, I have multiple monitors, so I'll try to work on this for 1.6.2.

**Comment by FinalSh4re** [comment]
I got the confirmation that it's working with the new version. Thanks, for implementing this so quickly.
