### ISSUE TITLE
_tkinter.TclError: invalid command name "::msgcat::mcload" 

### ISSUE THREAD

**Issue by funchan24** [israel-dryer/ttkbootstrap#184]
ttkbootstrap 1.6.0

The python scripts run well. I pack it to exe with Nuitka, I got a error when  running the exe.

Traceback (most recent call last):
  File "D:\users\funchan\Documents\App\ShareFile\output\ShareFile\main\main.py", line 538, in <module>
  File "D:\users\funchan\Documents\App\ShareFile\output\ShareFile\main\main.py", line 530, in main
  File "D:\users\funchan\Documents\App\ShareFile\output\ShareFile\main\main.py", line 103, in __init__
  File "D:\users\funchan\Documents\App\ShareFile\output\ShareFile\main\gui.py", line 42, in __init__
  File "D:\users\funchan\Documents\App\ShareFile\output\ShareFile\main\ttkbootstrap\window.py", line 188, in __init__
  File "D:\users\funchan\Documents\App\ShareFile\output\ShareFile\main\ttkbootstrap\style.py", line 494, in __init__
  File "D:\users\funchan\Documents\App\ShareFile\output\ShareFile\main\ttkbootstrap\localization\__init__.py", line 21, in initialize_localities
  File "D:\users\funchan\Documents\App\ShareFile\output\ShareFile\main\ttkbootstrap\localization\__init__.py", line 111, in load
_tkinter.TclError: invalid command name "::msgcat::mcload"

**Comment by israel-dryer** [comment]
@funchan24, what settings are you using with Nuitka? Are you using an Anaconda or Conda distribution of python?

**Comment by funchan24** [comment]
@israel-dryer I use venv, Nuitka '0.6.19.6' on Python '3.7'. the command is ` nuitka --standalone --output-dir=output\ShareFile --remove-output --windows-icon-from-ico=res\main.ico --plugin-enable=tk-inter core\main.py`

**Comment by israel-dryer** [comment]
@funchan24, the issue (I think) is with the --standalone option. This loads the packages into a temporary folder at runtime and then the program does not know where to find them. I think I need to change to using package resources instead and I believe this issue will go way. Working on a solution, hopefully will have something by tomorrow.

**Comment by israel-dryer** [comment]
@funchan24, hmm... using importlib.resources did not fix the issue, which means that the problem is not in locating the msg files. However, I'll probably still change to using importlib.resources because it can cause issues when using __file__ instead of using a more standard means. 

So, this likely means that Nuitka is not loading all of the tcl packages that are necessary to make '::msgcat::mcload' work in a standalone exe. This is what the plugin tk-inter is intended to solve. For now I'm at a loss for a solution.

**Comment by israel-dryer** [comment]
This might potentially be a better solutions for translations using a standard python module
https://docs.python.org/3/library/gettext.html#module-gettext

**Comment by funchan24** [comment]
@israel-dryer  Thank you very much, I will ask Nuitka‘s author for help. Now, I use ttkbootstrap 1.5.1 to pack exe. Maybe commenting out localization related code is  a temporary method.

**Comment by israel-dryer** [comment]
> @israel-dryer  Thank you very much, I will ask Nuitka‘s author for help. Now, I use ttkbootstrap 1.5.1 to pack exe. Maybe commenting out localization related code is  a temporary method.

I'll put some error handling around those methods to prevent it from crashing.

**Comment by israel-dryer** [comment]
I did have success using pyinstaller with these settings. I'm not sure how to perform the same on Nuitika. After testing this about a million ways, I think that Nuitka is not collecting the package resources from ttkbootstrap. I can force this with pyinstaller by using the command below. I'm sure there must be something similar with Nuitka.

```terminal
pyinstaller --onefile --collect-all ttkbootstrap myapp.py
```

**Comment by syoyo** [comment]
@israel-dryer FYI the fix(v1.7.0) still does not work well when running pyinstaller-packaged Windows .exe(`pyinstaller --collect-data ttkbootstrap myapp.py`) on a file path which contains whitespaces(e.g. "C:\path to\myapp\myapp.exe") 

```
...
File "ttkbootstrap\window.py", line 259, in __init__
File "ttkbootstrap\style.py", line 494, in __init__
File "ttkbootstrap\localization\__init__.py", line 23, in initialize_localities                                         File "ttkbootstrap\localization\msgcat.py", line 93, in load
_tkinter.TclError: wrong # args: should be "::msgcat::mcload langdir"  
```

Possible fix is wrap a path with double-quotes(only on Windows?):

https://github.com/israel-dryer/ttkbootstrap/blob/c4e4d86201f152b9f5d5bb22e39b3454234539a6/src/ttkbootstrap/localization/__init__.py#L18

```
MSGS_PATH = '"{}"'.format(f.parent.as_posix())
```

As you experienced, `--onefile` version works well.

**Comment by syoyo** [comment]
@israel-dryer Thanks! I will test a fix #194 soon!

**Comment by israel-dryer** [comment]
> @israel-dryer Thanks! I will test a fix #194 soon!

I pushed this in version 1.7.1

**Comment by syoyo** [comment]
@israel-dryer Thanks! v1.7.1 solved my issue!

**Comment by funchan24** [comment]
I still use ttkbootstrap 1.5.1 because i can‘t solve this problem.

**Comment by israel-dryer** [comment]
> I still use ttkbootstrap 1.5.1 because i can‘t solve this problem.

With Nuitka specifically, or PyInstaller?

**Comment by funchan24** [comment]
> > I still use ttkbootstrap 1.5.1 because i can‘t solve this problem.
> 
> With Nuitka specifically, or PyInstaller?

@israel-dryer Nuitka, lol.

**Comment by funchan24** [comment]
Nuitka will solve this problem. https://github.com/Nuitka/Nuitka/issues/1440

**Comment by israel-dryer** [comment]
That's great news! Thanks for seeing this through.

**Comment by Zyermy** [comment]
After I used pyinstaller to package it, I tried to open the exe file. Unfortunately, it reported an error TclError: invalid command name "::msgcat::mcmset". Please tell me how to solve it.
