### ISSUE TITLE
How to use custom text validation inside of a class?

### ISSUE THREAD

**Issue by Dan34523** [israel-dryer/ttkbootstrap#185]
The following code is a recreation of the error thrown in my project:

    import ttkbootstrap as ttk
    from ttkbootstrap.validation import add_validation, validator
    from tkinter import StringVar
    
    
    class CustomEntry(ttk.Frame):
        def __init__(self, master, label_text: str):
            super().__init__(master)
    
            self.value = StringVar()
            self.label = ttk.Label(self, text=label_text)
            self.entry = ttk.Entry(self, textvariable=self.value)
    
            self.label.pack(fill="x", anchor="w", padx=10, pady=5)
            self.entry.pack(fill="x", anchor="w", padx=10, pady=5)
    
            add_validation(self.entry, self.validate_text, when="key")
    
        @validator
        def validate_text(self, event):
            return 10 < len(event.postchangetext) < 20
    
    
    root = ttk.Window(minsize=(200, 60))
    entry = CustomEntry(root, "Test Entry")
    entry.pack(fill="both", expand=True)
    root.bind_all("<Button-1>", lambda event: event.widget.focus_set())
    root.mainloop()

When typing in the resulting entry box, the following error occurs:

    Exception in Tkinter callback
    Traceback (most recent call last):
      File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
        return self.func(*args)
      File "D:\Repo\Stinger\venv\lib\site-packages\ttkbootstrap\validation.py", line 157, in <lambda>
        f = widget.register(lambda *e: func(*e, **kwargs))
      File "D:\Repo\Stinger\venv\lib\site-packages\ttkbootstrap\validation.py", line 124, in inner
        event = ValidationEvent(*args)
    TypeError: ValidationEvent.__init__() takes 9 positional arguments but 10 were given

What could be causing this? Is the fact the validation is in the class causing issues?

**Comment by israel-dryer** [comment]
@Dan34523, using @ decorators inside a class are tricky.  Instead, you can wrap the function directly:

```python
import ttkbootstrap as ttk
from ttkbootstrap.validation import add_validation, validator
from tkinter import StringVar


class CustomEntry(ttk.Frame):
    def __init__(self, master, label_text: str):
        super().__init__(master)

        self.value = StringVar()
        self.label = ttk.Label(self, text=label_text)
        self.entry = ttk.Entry(self, textvariable=self.value)

        self.label.pack(fill="x", anchor="w", padx=10, pady=5)
        self.entry.pack(fill="x", anchor="w", padx=10, pady=5)

        # explicitly decorate the _validate_text method
        self.validate_text = validator(self._validate_text)

        # add the validation with the wrapped method
        add_validation(self.entry, self.validate_text, when="key")

    def _validate_text(self, event):
         return 10 < len(event.postchangetext) < 20

root = ttk.Window(minsize=(200, 60))
entry = CustomEntry(root, "Test Entry")
entry.pack(fill="both", expand=True)
root.bind_all("<Button-1>", lambda event: event.widget.focus_set())
root.mainloop()

```

**Comment by funchan24** [comment]
@israel-dryer I build a minimal code and got the same error.
`from ttkbootstrap import *

root = Window()
Label(root, text='Hello World').pack()
root.mainloop()`
