### ISSUE TITLE
[BUG] tableview: build_table_data vs insert_rows

### ISSUE THREAD

**Issue by dmalves** [israel-dryer/ttkbootstrap#208]
### Desktop (please complete the following information):

OS: Linux 64bits
ttkbootstrap : 1.7.1
python: 3.9.7

### Describe the bug

Hi, 

``` python

        valor = self._radio.get()

        dados_linhas = self._dadosTipoPlano(valor)

       # DELETE ALL ROWS
        self._tabela.delete_rows()

        # REBUILD TABLE
        self._tabela.build_table_data(
            coldata=self._dados_colunas,
            rowdata=dados_linhas,
        )
        # WHY NOT INSERT?
        # self._tabela.insert_rows("end", dados_linhas)
        self._tabela.load_table_data()
```

Given the code above, if I comment out "build_table_data" and uncomment "insert_rows" I get the same table, but there is an error when I click on the headers. 

`
File "/home/daniel/.pyenv/versions/3.9.7/envs/sistema_3.9.7/lib/python3.9/site-packages/ttkbootstrap/tableview.py", line 1315, in sort_column_data
    index = column.tableindex
AttributeError: 'NoneType' object has no attribute 'tableindex'
`

### To Reproduce

Code bellow is adapted from [https://github.com/israel-dryer/ttkbootstrap/blob/master/tests/widgets/tableview.py](url)

``` python
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from pathlib import Path
import csv
from ttkbootstrap.tableview import TableRow, Tableview
from ttkbootstrap.utility import scale_size
  
app = ttk.Window(themename="flatly")
colors = app.style.colors
  
p = Path(__file__).parent / "Sample1000.csv"
with open(p, encoding="utf-8") as f:
    reader = csv.reader(f)
    next(reader)
    rowdata = list(reader)
  
# column configuration options
# text, image, command, anchor, width, minwidth, maxwidth, stretch
coldata = [
    {"text": "SerialNumber", "stretch": False},
    "CompanyName",
    "Employee",
    "Description",
    {"text": "Leave", "stretch": False},
]

dt = Tableview(
    master=app,
    coldata=coldata,
    rowdata=rowdata,
    paginated=True,
    searchable=True,
    bootstyle=PRIMARY,
    stripecolor=(None, None),
    autofit=False,
)
dt.pack(fill=BOTH, expand=YES, padx=5, pady=5)
  
  
#  ----- BUG -------
# delete every row
dt.delete_rows()
# insert rows again
dt.insert_rows(index="end", rowdata=rowdata)
dt.load_table_data()
 
# NOW CLICK headers!

#  ----- BUG -------
  
app.mainloop()
```

### Expected behavior

When the headers are clicked, columns should be sorted.

**Comment by israel-dryer** [comment]
@dmalves, this closed automatically when I merged the branch. However, can you confirm that this fixed your issue. It fixed it on my end, but I want to make sure before I push a new release.
