### ISSUE TITLE
How to add vertical tabs to the Notebook widget?

### ISSUE THREAD

**Issue by QWKk** [israel-dryer/ttkbootstrap#210]
### Desktop (please complete the following information):

win10

### Describe the bug

Notebook.Whether it has longitudinal?

**Comment by QWKk** [comment]
![image](https://user-images.githubusercontent.com/58714401/154874992-2dff4386-54e4-4eef-8ffe-472eae502657.png)
I want to look like this

**Comment by QWKk** [comment]
instead of
![image](https://user-images.githubusercontent.com/58714401/154875046-d2c473d3-b18e-490f-8a57-34c27843d1fe.png)

**Comment by israel-dryer** [comment]
There is nothing built in currently to do this. However, you can make something like this by creating your own style.

<img width="187" alt="python_tbUQvBhZl2" src="https://user-images.githubusercontent.com/42584742/154878712-09be4960-0343-4476-bfb8-b3f5c6e72325.png">

```python
import ttkbootstrap as ttk
from ttkbootstrap.constants import *

app = ttk.Window()
app.style.configure('long.TNotebook', tabposition='wn')
nb = ttk.Notebook(app, style='long.TNotebook')

nb.pack(fill=BOTH, expand=YES)

for x in range(5):
    tabname = f'Tab {x}'
    nb.add(child=ttk.Notebook(width=300, height=300), text=tabname)

app.mainloop()
```

You could also choose to create a frame containing a bunch of buttons with the LINK bootstyle. If you don't like the focus ring on those and you want an exact look that you are getting in your picture, you can always remove the focus ring by setting the focuscolor on the style to an empty string.

```python
app.style.configure('link.Tbutton', focuscolor='')
```

**Comment by QWKk** [comment]
In this way, how to add image and child tab to the options?I tried to add but both failed.
![image](https://user-images.githubusercontent.com/58714401/154901902-3a014e23-1002-49ff-b309-b0f98a74f5fe.png)

**Comment by QWKk** [comment]
All right, thank you
