### ISSUE TITLE
Add a rounded and squared togglebutton

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/ttkbootstrap#22]
@daniilS, the toggle style you added gave me the ability to create a rounded toggle switch. I'm modeling it after the one [here](https://www.w3schools.com/howto/howto_css_switch.asp).  I'd like to have rounded and squared with images generated in the application at run-time so that I don't have to package the assets with the program. This also gives the ability to generate hover effects by dimming the color slightly with the ``update_hsv`` method.

The approach I took was to draw a rounded rectangle very large, and then shrink it to the size I need, apply anti-aliasing to get a nice smooth look. I'm not completely happy with the size or dimensions. But, it is getting close.

Let me know what you think if you have time to play around with it; and of course if you have any feedback.

![rounded-toggle](https://user-images.githubusercontent.com/42584742/114652088-32c85180-9cb3-11eb-813b-4677277830e4.gif)

```python
from PIL import Image, ImageTk, ImageDraw
from tkinter import ttk


on_color='#2196F3'
off_color = '#cccccc'

# off image
off_im = Image.new('RGBA', (226, 130))
draw = ImageDraw.Draw(off_im)
draw.rounded_rectangle([1, 1, 225, 129], radius=(128/2), fill=off_color)
draw.ellipse([14, 14, 114, 114], fill='white')

# on image
on_im = Image.new('RGBA', (226, 130))
draw = ImageDraw.Draw(on_im)
draw.rounded_rectangle([1, 1, 225, 129], radius=(128/2), fill=on_color)
draw.ellipse([12, 12, 116, 116], fill='white')
on_im = on_im.transpose(Image.ROTATE_180)

# set up application styles
style = ttk.Style()
style.theme_use('clam')

# set the background white
style.configure('white.TFrame', background='white')
window = ttk.Frame(style.master, style='white.TFrame', padding=20)
window.pack(fill='both', expand='yes')

# save reference to images
toggle_off = ImageTk.PhotoImage(off_im.resize((32, 20), Image.LANCZOS))
toggle_on = ImageTk.PhotoImage(on_im.resize((32, 20), Image.LANCZOS))

# create a new image element
style.element_create('rounded.Toolbutton.label', 'image', toggle_on, ('!selected', toggle_off))

# set the new layout
style.layout('rounded.Toolbutton', [
    ('Toolbutton.border', {'sticky': 'nswe', 'children': [
        ('Toolbutton.padding', {'sticky': 'nswe', 'children': [
            ('rounded.Toolbutton.label', {'sticky': 'nswe'})]})]})])

# configure style settings
style.configure('rounded.Toolbutton', relief='flat', borderwidth=0)
style.map('rounded.Toolbutton',
          background=[
              ('selected', 'white'),
              ('!selected', 'white')])



# demo the new widget
ttk.Checkbutton(window, style='rounded.Toolbutton').pack()
window.mainloop()




```

**Comment by israel-dryer** [comment]
fixed the layout to add a label to the right. Also, right-sized the toggle to match the radio and checkbuttons.

![image](https://user-images.githubusercontent.com/42584742/114681728-6d92af80-9cdc-11eb-8124-aff5f3ece4d8.png)

```python
from tkinter import ttk

from PIL import Image, ImageTk, ImageDraw
from ttkbootstrap import Style

on_color = '#2196F3'
off_color = '#b4bcc2'

# off image
off_im = Image.new('RGBA', (226, 130))
draw = ImageDraw.Draw(off_im)
draw.rounded_rectangle([1, 1, 225, 129], radius=(128 / 2), outline=off_color, width=6)
draw.ellipse([20, 18, 112, 110], fill=off_color)

# on image
on_im = Image.new('RGBA', (226, 130))
draw = ImageDraw.Draw(on_im)
draw.rounded_rectangle([1, 1, 225, 129], radius=(128 / 2), fill=on_color)
draw.ellipse([18, 18, 110, 110], fill='white')
on_im = on_im.transpose(Image.ROTATE_180)

style = Style()

# set the background white
style.configure('white.TFrame', background='white')
window = ttk.Frame(style.master, style='white.TFrame', padding=20)
window.pack(fill='both', expand='yes')

# save reference to images
toggle_off = ImageTk.PhotoImage(off_im.resize((24, 15), Image.LANCZOS))
toggle_on = ImageTk.PhotoImage(on_im.resize((24, 15), Image.LANCZOS))

# create a new image element
style.element_create('Toolbutton.toggle', 'image', toggle_on,
                     ('!selected', toggle_off),
                     width=28, border=4, sticky='w')

# set the new layout
style.layout('rounded.Toolbutton', [
    ('Toolbutton.border', {'sticky': 'nswe', 'children': [
        ('Toolbutton.padding', {'sticky': 'nswe', 'children': [
            ('Toolbutton.toggle', {'side': 'left'}),
            ('Toolbutton.label', {'side': 'left'})]})]})])

# configure style settings
style.configure('rounded.Toolbutton', relief='flat', borderwidth=0)
style.map('rounded.Toolbutton',
          background=[
              ('selected', 'white'),
              ('!selected', 'white')])

# demo the new widget
ttk.Checkbutton(window, text='toggle switch', style='rounded.Toolbutton').pack(fill='x')
ttk.Checkbutton(window, text='checkbox').pack(fill='x', pady=10)
ttk.Radiobutton(window, text='radiobutton').pack(fill='x')
window.mainloop()

```

**Comment by israel-dryer** [comment]
added squared toggle

![image](https://user-images.githubusercontent.com/42584742/114683795-52c13a80-9cde-11eb-9663-9b833f6d54ad.png)

```python
from tkinter import ttk

from PIL import Image, ImageTk, ImageDraw
from ttkbootstrap import Style

on_color = '#2196F3'
off_color = '#b4bcc2'

style = Style()

# set the background white
style.configure('white.TFrame', background='white')
window = ttk.Frame(style.master, style='white.TFrame', padding=20)
window.pack(fill='both', expand='yes')

# rounded toggle -------------------------------------------------------------------------------------------------------

# rounded off image
rounded_off_im = Image.new('RGBA', (226, 130))
draw = ImageDraw.Draw(rounded_off_im)
draw.rounded_rectangle([1, 1, 225, 129], radius=(128 / 2), outline=off_color, width=6)
draw.ellipse([20, 18, 112, 110], fill=off_color)

# rounded on image
rounded_on_im = Image.new('RGBA', (226, 130))
draw = ImageDraw.Draw(rounded_on_im)
draw.rounded_rectangle([1, 1, 225, 129], radius=(128 / 2), fill=on_color)
draw.ellipse([18, 18, 110, 110], fill='white')
rounded_on_im = rounded_on_im.transpose(Image.ROTATE_180)
rounded_toggle_off = ImageTk.PhotoImage(rounded_off_im.resize((24, 15), Image.LANCZOS))
rounded_toggle_on = ImageTk.PhotoImage(rounded_on_im.resize((24, 15), Image.LANCZOS))

# create indicator element
style.element_create('Toolbutton.rounded.toggle', 'image', rounded_toggle_on,
                     ('!selected', rounded_toggle_off),
                     width=28, border=4, sticky='w')

# set the new layout
style.layout('rounded-toggle.Toolbutton', [
    ('Toolbutton.border', {'sticky': 'nswe', 'children': [
        ('Toolbutton.padding', {'sticky': 'nswe', 'children': [
            ('Toolbutton.rounded.toggle', {'side': 'left'}),
            ('Toolbutton.label', {'side': 'left'})]})]})])

# configure style settings
style.configure('rounded-toggle.Toolbutton', relief='flat', borderwidth=0)
style.map('rounded.Toolbutton',
          background=[
              ('selected', 'white'),
              ('!selected', 'white')])

# squared toggle -------------------------------------------------------------------------------------------------------

# square off image
squared_off_im = Image.new('RGBA', (226, 130))
draw = ImageDraw.Draw(squared_off_im)
draw.rectangle([1, 1, 225, 129], outline=off_color, width=6)
draw.rectangle([20, 18, 112, 110], fill=off_color)

# squared on image
squared_on_im = Image.new('RGBA', (226, 130))
draw = ImageDraw.Draw(squared_on_im)
draw.rectangle([1, 1, 225, 129], fill=on_color)
draw.rectangle([18, 18, 110, 110], fill='white')
squared_on_im = squared_on_im.transpose(Image.ROTATE_180)
squared_toggle_off = ImageTk.PhotoImage(squared_off_im.resize((24, 15), Image.LANCZOS))
squared_toggle_on = ImageTk.PhotoImage(squared_on_im.resize((24, 15), Image.LANCZOS))

# create indicator element
style.element_create('Toolbutton.squared.toggle', 'image', squared_toggle_on,
                     ('!selected', squared_toggle_off),
                     width=28, border=4, sticky='w')

# set the new layout
style.layout('squared-toggle.Toolbutton', [
    ('Toolbutton.border', {'sticky': 'nswe', 'children': [
        ('Toolbutton.padding', {'sticky': 'nswe', 'children': [
            ('Toolbutton.squared.toggle', {'side': 'left'}),
            ('Toolbutton.label', {'side': 'left'})]})]})])

# configure style settings
style.configure('squared-toggle.Toolbutton', relief='flat', borderwidth=0)
style.map('squared.Toolbutton',
          background=[
              ('selected', 'white'),
              ('!selected', 'white')])

# demo the new widget
ttk.Checkbutton(window, text='toggle switch', style='rounded-toggle.Toolbutton').pack(fill='x', pady=10)
ttk.Checkbutton(window, text='toggle switch', style='squared-toggle.Toolbutton').pack(fill='x')
ttk.Checkbutton(window, text='checkbox').pack(fill='x', pady=10)
ttk.Radiobutton(window, text='radiobutton').pack(fill='x')
window.mainloop()

```

**Comment by daniilS** [comment]
Oh, that's a good idea! Out of interest, how does the performance compare to using an asset, or a base64 string (or maybe even a canvas) for the image? My main reason for using this library in the first place was because the graphical themes from ttkthemes became incredibly laggy when creating or resizing windows with a lot of image-based widgets.

**Comment by israel-dryer** [comment]
that's a good question, and one that's been on my mind for a few weeks. Because I'm not drawing every border with an image as in ttkthemes, I don't think I'd have the same issues, but I'm just speculating.  I've tried to keep the images microscopic in size to avoid that. I'll open an issue on this, because there are some related issues I want to explore because it could *potentially* become an issue in the future because I'm essentially creating all themes (and theme assets) at runtime for every theme.

**Comment by daniilS** [comment]
For ttkthemes, my issue was that I have a toplevel window with a large grid of entry widgets, and creating/resizing/scrolling became a lot slower as the table got more rows. That should hopefully mean that it's just the (re)drawing of a lot of images that affects performance, so just creating the theme could be fine.

**Comment by israel-dryer** [comment]
oh yeah. creating a grid can be expensive. I haven't done it yet, but I've thought of having something where a table is a set size, and instead of adding more table rows, you actually just page through the data and the rows update so that it gives the appearance that you are scrolling down the page, but in reality it is simply updating the existing widgets with a paginated list if data points.

**Comment by israel-dryer** [comment]
light theme color variations for `Roundtoggle.Toolbutton`

![image](https://user-images.githubusercontent.com/42584742/114779604-5091c700-9d44-11eb-99bd-5c72f3d5b6e5.png)

dark theme color variations for `Roundtoggle.Toolbutton`

![image](https://user-images.githubusercontent.com/42584742/114779796-8b93fa80-9d44-11eb-99e5-26bf6dbd91dc.png)

**Comment by daniilS** [comment]
I've actually tried that approach to scrolling before! But it turned out that for graphical themes, for some reason even just updating an entry's content is very slow. If you want to test it yourself, the Adapta theme from ttkthemes is particularly laggy. Here's an example to test all three of creating, updating, and resizing a table:

https://gist.github.com/daniilS/069c7a544d007083e7c502e929069db2

**Comment by israel-dryer** [comment]
squared toggle buttons

**light theme**

![image](https://user-images.githubusercontent.com/42584742/114783747-2cd08000-9d48-11eb-8ba3-ea87581c902a.png)

**dark theme**

![image](https://user-images.githubusercontent.com/42584742/114783786-3c4fc900-9d48-11eb-921f-01970e328dd7.png)

**Comment by israel-dryer** [comment]
> 
> 
> I've actually tried that approach to scrolling before! But it turned out that for graphical themes, for some reason even just updating an entry's content is very slow. If you want to test it yourself, the Adapta theme from ttkthemes is particularly laggy. Here's an example to test all three of creating, updating, and resizing a table:
> 
> https://gist.github.com/daniilS/069c7a544d007083e7c502e929069db2
> 
> EDIT: I guess a similar script could also easily be used to tell whether there's any difference in performance between an image asset, dynamic image generation, or a base64 string for toggle switches

From what I remember, base64 tends to dramatically increase the data size of the image, so there would potentially be a penalty there. It would be interesting to stress test the various scenarios though to see what is gained in load-times vs. lag and memory consumption.

**Comment by daniilS** [comment]
I've tried it with a very large grid of togglebuttons, and while it's obviously slower than a regular Toolbutton, the performance feels fine if there's not too many of them, so this approach should be fine. However, the round toggle buttons currently have the circles in the same colour as the background when using a light theme.

**Comment by israel-dryer** [comment]
yikes. not sure how I missed that. Fixed the colors. I decided to go with the outline on the off colors as it just looked sharper.

![image](https://user-images.githubusercontent.com/42584742/114805796-9dd85d80-9d71-11eb-8191-e08e2eefe0ce.png)
![image](https://user-images.githubusercontent.com/42584742/114805821-a9c41f80-9d71-11eb-8a1c-8c9262d82a80.png)

**Comment by israel-dryer** [comment]
this almost makes me want to draw my own radio and check buttons...
