### ISSUE TITLE
Custom Font Size Keyword Argument

### ISSUE THREAD

**Issue by lolghuiy4tgfyu4th7tvtg** [israel-dryer/ttkbootstrap#221]
### Is your feature request related to a problem? Please describe.

I wanted to create a large label on the top of my app, and I knew that to change the font size, I would also have to change the font too.

### Describe the solution you'd like

A ```font_size``` keyword argument to change the font size.

### Describe alternatives you've considered

I have considered using a font like Arial, but I think there could also be a system of certain font sizes, like how html has <h1-6>

**Comment by israel-dryer** [comment]
I believe you can do this already. Try using `font=(None, 16)` or `font="-size 16" `

**Comment by lolghuiy4tgfyu4th7tvtg** [comment]
Okay
