### ISSUE TITLE
No module named 'ttkbootstrap.constants' 

### ISSUE THREAD

**Issue by chineselzh** [israel-dryer/ttkbootstrap#228]
### Desktop (please complete the following information):

ttkbootstrap Version [e.g. 1.7.3]
OS: [e.g. Win11]

when i run the code:

```python
import tkinter as tk
import ttkbootstrap as ttk
from ttkbootstrap.constants import *

root = tk.Tk()

b1 = ttk.Button(root, text="Button 1", bootstyle=SUCCESS)
b1.pack(side=LEFT, padx=5, pady=10)

b2 = ttk.Button(root, text="Button 2", bootstyle=(INFO, OUTLINE))
b2.pack(side=LEFT, padx=5, pady=10)

root.mainloop()

```
I get the error：`No module named 'ttkbootstrap.constants`
how can i use ttkbootstrap.constants?

### Describe the bug

Traceback (most recent call last):
  File "D:\桌面\ttkbootstrap.py", line 2, in <module>
    import ttkbootstrap as ttk
  File "D:\桌面\ttkbootstrap.py", line 3, in <module>
    from ttkbootstrap.constants import *
ModuleNotFoundError: No module named 'ttkbootstrap.constants'; 'ttkbootstrap' is not a package

![image](https://user-images.githubusercontent.com/11897604/158153075-829d71cf-c8a3-4bdc-a3dc-2db94e182625.png)

**Comment by israel-dryer** [comment]
@chineselzh, it appears from the traceback that ttkbootstrap is not installed.

**Comment by PySimpleGUI** [comment]
I saw your "everything_bagel.py"  file and had to give it a try!

![image](https://user-images.githubusercontent.com/46163555/162329692-724368a4-0027-475f-b64a-a8c70afcfb8a.png)

But I ran into the problem reported in this issue.

https://github.com/israel-dryer/ttkbootstrap/blob/2a298e6a3d80f499da142d978ed298eb349c739e/gallery/everything_bagel.py#L2

I uninstalled and reinstalled ttkbootstrap just to be sure

![image](https://user-images.githubusercontent.com/46163555/162329821-32acb032-8e2b-4ee6-a13e-5ef10573a686.png)


But I still got the same error:

![image](https://user-images.githubusercontent.com/46163555/162329872-708863a9-caa2-4f83-9715-ace911e8f56b.png)

**Comment by ldfinfontainebleau** [comment]
I got same error, and i have installed ttkbootstrap 0.5.3 from pip.

**Comment by jongden** [comment]
I got the same error. Have you fixed this error?

**Comment by enriqueviera** [comment]
I'm getting this same error in Unbuntu Budgie 22.04.1 and MacOS Monterrey. No matter what I do cannot pass this error. I'm also getting similar errors for TableView. Am I'm missing something?

**Comment by rdbende** [comment]
What's the name of your file?

**Comment by jongden** [comment]
> 
Do not create files using ttkbootstrap.py. It's better to call it something else.

**Comment by jongden** [comment]
@enriqueviera

**Comment by enriqueviera** [comment]
thank's for the input @jongden, I had a file called  ttkbootstrap.py in the same folder. My mistake for not knowing that imports can use files in the same folder when the name of the library corresponds (just started learning python).
