### ISSUE TITLE
DeprecationWarning: CUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.

### ISSUE THREAD

**Issue by demberto** [israel-dryer/ttkbootstrap#243]
### Desktop (please complete the following information):

ttkbootstrap 1.7.1
OS: Windows 10

### Describe the bug

ttkbootstrap\style.py:2143: DeprecationWarning: CUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
    image = ImageTk.PhotoImage(img.resize(size), Image.CUBIC)

### To Reproduce

I found this out when running a test with pytest.

**Comment by israel-dryer** [comment]
Thank you. I'll make sure this is updated in the next release.
