### ISSUE TITLE
Entry not working after showing messagebox

### ISSUE THREAD

**Issue by youstanzr** [israel-dryer/ttkbootstrap#246]
### Desktop (please complete the following information):

Python 3.7
tkinter.Tcl version 8.6.8
ttkbootstrap version 1.7.4
OS: Mac OS

### Describe the bug

I have created a simple app with a label, entry and button. Pressing the button shows a message box with some text. I have found that the entry stops working after the message box appears. I have simplified my code into the basics to test this and the issue still persist.

### To Reproduce

1- Test the entry by writing anything
2- Press the button so that the message box appears
3- Click ok to close the message box
4- Try again to type in the entry, it won't work

### Expected behavior

Expected the entry to function normally after the message box is closed

### Screenshots

[https://imgur.com/a/skgYwKm]()

### Additional context

Here is the code
```
class TestApp(ttk.Window):
	def __init__(self):
		super().__init__(title='My App', themename='litera')
		label = ttk.Label(self,
						text='Hi there!',
						font=("Helvetica", 24))
		label.pack(side="top", fill="x", expand=True, padx=5, pady=2)

		entry = ttk.Entry(self)
		entry.pack(side="top", fill="x", padx=5, pady=2)

		button = ttk.Button(self, text = 'Press here', bootstyle=DANGER, width=1, command=self.button_clicked)
		button.pack(side="top", fill="x", padx=(0,5), pady=2)

	def button_clicked(self):
		ttk.dialogs.dialogs.Messagebox.ok(title='Action', message='Button has been pressed')


if __name__ == "__main__":
	app = TestApp()
	app.mainloop()

```

**Comment by israel-dryer** [comment]
This is the expected behavior. The messagebox [takes the focus and grabs all screen events](https://github.com/israel-dryer/ttkbootstrap/blob/2a298e6a3d80f499da142d978ed298eb349c739e/src/ttkbootstrap/dialogs/dialogs.py#L89), and the `wait_window` method prevents anything else from happening until you confirm the message by pressing 'ok' on the message box. Then, the result is saved and focus is returned to the parent window.

**Comment by israel-dryer** [comment]
@youstanzr, I'm not able to replicate this issue on my Mac-mini.  What version of tcl are you currently running?

```python
import tkinter
tcl = tkinter.Tcl()
print(tcl.call("info", "patchlevel"))
```

**Comment by youstanzr** [comment]
Python version 3.7
tcl version 8.6.8

**Comment by youstanzr** [comment]
Updated the post to include my python and tcl versions

**Comment by youstanzr** [comment]
@rdbende Where do I add this? I tried to add it in the button_clicked function but it ends up blocking the messagebox.

Which python and tkinter.Tcl version are you using?

**Comment by rdbende** [comment]
It's not at your side, but @israel-dryer should add it to ttkbootstrap in `dialogs.py` at line 89

I use Py3.8 and and Tcl8.6.9

**Comment by youstanzr** [comment]
I am still not sure the cause of this issue but it seems to be fixed by updating my python and tkinter
**my setup:**
Python version 3.10.2
tkinter.Tcl version 8.6.12

**Comment by rdbende** [comment]
Strange anyways
