### ISSUE TITLE
Tkinter path handling under Windows with `MessageCatalog.load`

### ISSUE THREAD

**Issue by demberto** [israel-dryer/ttkbootstrap#253]
### Desktop (please complete the following information):

OS: Windows 10 64-bit
Python: 3.9.7
tkinter: 8.6.9
ttkbootstrap: 1.7.4

### Describe the bug

I used the `load` method to load all translation files in a directory.

Under Windows atleast the `load` method needs:

1. An absolute-resolved path.
2. All backslashes replaced with forward slashes

You can fix your implementation by just resolving the path and replacing any backslashes with forward slashes. I can drop a PR if you wish.

### Additional context

This is most probably a Tkinter bug, or might be a Tk bug as well.

**Comment by demberto** [comment]
This seems to be a Tk < 8.6.10 *i.e. Python < 3.10 bug*.

**Comment by rdbende** [comment]
You could also use the builtin pathlib module like so:
```python
MessageCatalog.load(str(pathlib.Path("./relative/path/to/your/translation.file").resolve()))
```
And this way you don't even have to bother with back/forward slashes.

**Comment by demberto** [comment]
@rdbende The `resolve()` method turns all forward slashes to backslashes on Windows. Also ttkbootstrap's implementation is not what is recommended. The msgcat manual page recommends using this command:

```tcl
::msgcat::mcload [file join [file dirname [info script]] msgs]
```

*where **msgs** is the folder containing translations*

I don't know how ttkbootstrap's implementation works, but when I tried using the same code in my own application it didn't work, the above command worked.

**Comment by rdbende** [comment]
Oh, I see. It's strange though, that Tcl/Tk doesn't understand backslashes.

**Comment by israel-dryer** [comment]
I'll check into this. Something that might be easier is to use the `LocalMsgs` class to add your catalog via python. I created not to long ago so that users did not have to include data files when compiling the files into executables. This is also how I include built-in msgs in the Library currently, so that I didn't have to package a bunch of language.msg files.

```python
import ttkbootstrap as ttk
from ttkbootstrap.localization.msgs import LocaleMsgs
from ttkbootstrap.localization import MessageCatalog

root = ttk.Window()

# create an initialize the custom catalog
lm = LocaleMsgs(
    "en",
    ("Original 1", "Translation 1"),
    ("Original 2", "Translation 2"),
    ("Original 3", "Translation 3"),
)
lm.initialize()

# add labels to the window with the msg catalog
for _ in range(3):
    ttk.Label(
        root, 
        text=MessageCatalog.translate("Original 1")
    ).pack(padx=10, pady=10)

# show the window
root.mainloop()
```

![python_U8fkYugIYP](https://user-images.githubusercontent.com/42584742/163490890-382aecd7-980f-469a-9a6d-6b3b434ae80c.png)

**Comment by demberto** [comment]
@israel-dryer I did think of that, but IMO its just better to keep things decoupled. Plus its not difficult at all to include the `.msg` files in the source tarball and distribution wheels.

**Comment by israel-dryer** [comment]
> ```tcl
> ::msgcat::mcload [file join [file dirname [info script]] msgs]
> ```

using `Path.as_posix()` returns the path with all forward slashes.

**Comment by israel-dryer** [comment]
@demberto, as @rdbende suggested, you can use the "Path" object. But, using the `as_posix` method will _always return the path with forward slashes_. I have not experienced any issues with the implementation in ttkbootstrap personally. I've seen the tcl/tk recommended list iteration. It is just  another way to iterate through a path list; it works the same as what I've implemented.

To make things easier, I may convert the path or path object within the method itself. I would not say this is a bug though, just an enhancement.

```python
    @staticmethod
    def load(dirname):
        """Searches the specified directory for files that match the
        language specifications returned by `preferences`. Each file
        located is sourced.

        Parameters:

            dirname (str or Pathlike object):
                The directory path of the msg files.

        Returns:

            int:
                Then number of message files which matched the
                specification and were loaded.
        """
        from pathlib import Path
        msgs = Path(dirname).as_posix() # format path for tcl/tk
        
        root = get_default_root()
        command = "::msgcat::mcload"
        return int(root.tk.eval(f"{command} [list {msgs}]"))
```

**Comment by demberto** [comment]
@israel-dryer I agree, its a bug in Tk itself. Any Windows software should support backslashes in paths
