### ISSUE TITLE
CheckButton's ON state while it is disabled

### ISSUE THREAD

**Issue by atban98** [israel-dryer/ttkbootstrap#258]
### Is your feature request related to a problem? Please describe.

When setting the `state` of a `CheckButton` to `DISABLED`, the "tick" disappears from the `CheckButton` as its variable would have the `offvalue` value. 
A small reproducer:
```
import ttkbootstrap as ttk

app = ttk.Window()

frame = ttk.Frame(app)
frame.pack()

value = ttk.StringVar()
value.set("1")
ttk.Checkbutton(frame, text=f"Checkbutton", state=ttk.DISABLED, variable=value, onvalue="1", offvalue="0").pack()

app.mainloop()
```

### Describe the solution you'd like

I would like a `DISABLED` state for the `CheckButton` that properly indicates the state of its value(properly grayed out when the state is on).

### Describe alternatives you've considered

My workaround was not setting the `CheckButton` to `DISABLED`. Instead, I bound a callback function for the toggling. In the callback function, I set the bounded value manually to its previous value (if I want the button to be disabled) so the user feels like the button is actually disabled.

**Comment by israel-dryer** [comment]
@atban98, this is what I'm currently preparing for checkbutton styles. Any thoughts or comments on these proposed updates?

<img alt="image" src="https://user-images.githubusercontent.com/42584742/164143088-362a1ad5-21c4-4283-b7ef-b76b52e908c3.png">

**Comment by atban98** [comment]
@israel-dryer, that's pretty good, but I would prefer something like this:
![164143088-362a1ad5-21c4-4283-b7ef-b76b52e908c3](https://user-images.githubusercontent.com/62559545/164176961-a5e53a75-d4be-49ce-ad79-be2f77e8524d.png)
It gives me more the "disabled-selected" feeling.

**Comment by israel-dryer** [comment]
Yeah I like that too

**Comment by israel-dryer** [comment]
light theme results
<img width="202" alt="python_MRaDGnnOX1" src="https://user-images.githubusercontent.com/42584742/164247970-684c3153-f628-4d4d-a27a-ff764c89d78d.png">

dark theme results
<img width="202" alt="python_RyxR3yjrxe" src="https://user-images.githubusercontent.com/42584742/164247707-c32e0bb4-48fd-4495-986c-6a60167b6000.png">
