### ISSUE TITLE
Add custom radiobuttons for nicer look and cross-platform consistency

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/ttkbootstrap#26]
This is a potential improvement to create a consistent look & feel across platforms. Currently, the native windows buttons are used on windows, and standard *clam* theme on linux & mac.  Also, these custom buttons look like the *Bootstrap* styled buttons on bootswatch.com, so that's a plus.

I could create images for the hover and pressed effects, as I did for the scale indicator, but not sure if it's strictly necessary.

*light theme example*
![image](https://user-images.githubusercontent.com/42584742/114915620-c4d67400-9df1-11eb-8487-9c3d76abe813.png)

*dark theme example*
![image](https://user-images.githubusercontent.com/42584742/114915709-e6cff680-9df1-11eb-8acd-0601d593d967.png)

**Comment by israel-dryer** [comment]
example of new radio buttons on the *lumen* theme

![image](https://user-images.githubusercontent.com/42584742/114941451-3376fa00-9e11-11eb-89c4-1be8c41b3312.png)

example of the new radiobuttons on the *cyborg* theme

![image](https://user-images.githubusercontent.com/42584742/114941551-50abc880-9e11-11eb-8b6d-2851d98f7568.png)

**Comment by israel-dryer** [comment]
The style works well on light themes.. I'm not completely sold on the look for dark themes. Possibly I could make the colors inverse for background and indicator? It is consistent with the look on bootswatch, but that's not necessarily a reason to keep it.

**Comment by israel-dryer** [comment]
This uses a light background for the off color, so the look is more consistent. 

![image](https://user-images.githubusercontent.com/42584742/114943421-f8c29100-9e13-11eb-99f4-5c1535a7caf0.png)

**Comment by israel-dryer** [comment]
Inverse colors with a larger indicator

![image](https://user-images.githubusercontent.com/42584742/114944425-9074af00-9e15-11eb-8b8d-79cfde4ec005.png)

Inverse colors with a smaller indicator

![image](https://user-images.githubusercontent.com/42584742/114944493-b437f500-9e15-11eb-9b6d-a69d60eb089a.png)

**Comment by daniilS** [comment]
All those options look great! A slightly scaled down version with the large indicator is probably the closest to the native radiobutton.
