### ISSUE TITLE
Add Text widget parameters to ScrolledText

### ISSUE THREAD

**Issue by atban98** [israel-dryer/ttkbootstrap#265]
### Is your feature request related to a problem? Please describe.

I am working on a serial terminal application which uses the `Text` widget to display the output a serial port. The user shouldn't be able to write to this widget directly, so I changed its state to `DISABLED`.  (I also changed the `bg` to white. When a text arrives from the serial port, I change back the state to `NORMAL`, write the text, then disable it again, because the `Text` widget is not allowing to update its content while disabled.)

### Describe the solution you'd like

My plan is to use the `ScrolledText` widget instead, and I would like the `bg` and `state` parameters to be available for this widget. I think the other parameters of the `Text` widget also would be useful.

### Describe alternatives you've considered

-

**Comment by israel-dryer** [comment]
@atban98, the ScrolledText widget has a `text` property that you can use to access the internal text widget. Additionally, you can style the scrollbars using the pattern below.

https://ttkbootstrap.readthedocs.io/en/latest/api/scrolled/scrolledtext/

<img width="414" alt="python_QCf9jhRKFD" src="https://user-images.githubusercontent.com/42584742/164359017-00f70afc-2414-4769-8e43-f71f58aee957.png">

```python
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap.scrolled import ScrolledText, ScrolledFrame

app = ttk.Window()

st = ScrolledText(app, padding=5, height=10, hbar=True, autohide=True)
st.insert(END, 'Insert your text here.')
st.pack(fill=BOTH, expand=YES)

# configure internal text widget
st.text.configure(bg='red', fg='white', state=DISABLED)

# configure internal vertical scrollbar
st.vbar.configure(bootstyle=ROUND)

app.mainloop()
```
