### ISSUE TITLE
Floodguage throws error with variable parameter

### ISSUE THREAD

**Issue by atban98** [israel-dryer/ttkbootstrap#277]
### Desktop (please complete the following information):

ttkbootstrap Version 1.7.5
OS: Windows 10

### Describe the bug

When instantiating a `Floodguage` with `variable` parameter, the following error is thrown:

`TypeError: ttkbootstrap.style.Bootstyle.override_ttk_widget_constructor.<locals>.__init__() got multiple values for keyword argument 'variable'`

Removing the [variable assignment](https://github.com/israel-dryer/ttkbootstrap/blob/master/src/ttkbootstrap/widgets.py#L397) fixed the issue for me.

**Comment by israel-dryer** [comment]
@atban98, this widget doesn't actually have a variable parameter; I'm using it internally. However, I think to avoid confusion with the regular progressbar api and to prevent the issue you describe, it makes sense to check for a user variable argument before setting one internally.
