### ISSUE TITLE
Add more attributes to LabelFrame

### ISSUE THREAD

**Issue by atban98** [israel-dryer/ttkbootstrap#281]
### Is your feature request related to a problem? Please describe.

ttk has some [handy attributes](https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/ttk-LabelFrame.html) for `LabelFrame` widget. Would it be possible to implement some of them for ttkbootstrap? For example, the `font` and `labelanchor` attributes.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by israel-dryer** [comment]
Hi, you should be able to use any ttk option already. I do not believe font is one of those options, however. The labelanchor option is demonstrated below:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/42584742/166171686-536de1a5-1b6a-496c-9943-b0cbc8fc0000.png">
