### ISSUE TITLE
【ttkbootstrap==1.7.6)】pyinstaller to exe: _tkinter.TclError: invalid command name "::msgcat::mcload"

### ISSUE THREAD

**Issue by istarmeow** [israel-dryer/ttkbootstrap#284]
### Desktop (please complete the following information):

- ttkbootstrap==1.7.6
- OS==win10 or win11
- pyinstaller==5.0
- python=3.10、3.8、3.7

### Describe the bug

`pyinstaller  --clean -y -c --add-data=C:\Apps\Python\Python310\tcl\tcl8.6;.\tcl --add-data=C:\Apps\Python\Python310\tcl\tk8.6;.\tk --collect-data ttkbootstrap  test_ttkbs.py`

```bash
Traceback (most recent call last):
  File "test_ttkbs.py", line 21, in <module>
  File "ttkbootstrap\window.py", line 188, in __init__
  File "ttkbootstrap\style.py", line 494, in __init__
  File "ttkbootstrap\localization\__init__.py", line 22, in initialize_localities
  File "ttkbootstrap\localization\msgcat.py", line 93, in load
_tkinter.TclError: invalid command name "::msgcat::mcload"
[19012] Failed to execute script 'test_ttkbs' due to unhandled exception!

```

### To Reproduce

```py
import ttkbootstrap as ttk
from ttkbootstrap.constants import *

root = ttk.Window(themename="superhero")

b1 = ttk.Button(root, text="Submit", bootstyle="success")
b1.pack(side=LEFT, padx=5, pady=10)

b2 = ttk.Button(root, text="Submit", bootstyle="info-outline")
b2.pack(side=LEFT, padx=5, pady=10)

root.mainloop()
```

**Comment by istarmeow** [comment]
ttkbootstrap 1.5.1 work normally

**Comment by israel-dryer** [comment]
You shouldn't need to collect anything for this version of ttkbootstrap.

I was able to package the same program above using the following command.
```console
pyinstaller test_ttkbs.py
```

**Comment by istarmeow** [comment]
I know why!

I use **PyCharm** to create a virtual environment of Python, and then pack it in the Pyinstaller command, which will **fail**.

But I use the `python -m venv xxx` command to create a virtual environment, or use the Python installation package directly to run normally.

Thanks !!!

**Comment by istarmeow** [comment]
> I know why!
> 
> I use **PyCharm** to create a virtual environment of Python, and then pack it in the Pyinstaller command, which will **fail**.
> 
> But I use the `python -m venv xxx` command to create a virtual environment, or use the Python installation package directly to run normally.
> 
> Thanks !!!

**Already verified, because the virtual environment created contains `[]` symbols**, like
![image](https://user-images.githubusercontent.com/26065919/167166440-ce431ae4-7857-4bca-9c34-36e528adb68a.png)
