### ISSUE TITLE
Tableview : The order of multiple columns is not sorted correctly

### ISSUE THREAD

**Issue by TooLazy0x00** [israel-dryer/ttkbootstrap#286]
### Desktop (please complete the following information):

I am using tableview to generate the chart, but the arrangement order of the columns is not the same as the column names I defined
like this
-----------------------------------------------------------------------------
coldata = ('1', '2', '3', '4', '5', '6', '7', '8',
           '9', '10', '11', '12', '13', '14', '15',
           '16', '17')

root = ttk.Window()

colors = root.style.colors 

tree = Tableview(root, coldata=coldata, bootstyle=INFO, rowdata=data,
                 searchable=True, autofit=True, stripecolor=(colors.light, None))

tree.pack(expand=True, fill=BOTH)

root.mainloop()
----------------------------------------------------------------------------
The order in which the columns are actually generated in the chart is
1, 2, 11, 12, 13, 14, 15, 16, 3, 4, 5, 6, 7, 8, 9, 10, 17

### Describe the bug

The order of multiple columns is not sorted correctly

**Comment by Piping** [comment]
Hi, I triggered this bug with documentation example code. 

```python
def create_bitfield_table_view(self):
    """Show structture bitfield arrangement in tableview"""
    self.dt = Tableview(
            master=self,
            paginated=False,
            searchable=True,
            bootstyle=PRIMARY,
    )
    self.dt.insert_column(0, text='DW', width=40);
    for x in range(9,-1,-1):
        self.dt.insert_column('end', text=str(x), width=30, stretch=False);
    self.dt.pack(fill=BOTH, expand=YES, padx=10, pady=10)
```
Screenshot:
![image](https://user-images.githubusercontent.com/12042284/184277946-ad4177b1-af64-4d41-96bf-234742932254.png)

Once I added more than 9 columns:
screenshots:
![image](https://user-images.githubusercontent.com/12042284/184278045-57ca7fee-9632-405d-aff5-f2bc54d01e84.png)
