### ISSUE TITLE
Colors.hex_to_rgb works strange when use short color definition: like "#FFF"

### ISSUE THREAD

**Issue by arthurfait** [israel-dryer/ttkbootstrap#297]
### Desktop (please complete the following information):

ttkbootstrap Version  1.7.7.1
Linux Debian(testing)

### Describe the bug

Colors.hex_to_rgb converts "#FFF"
to (0.06, 0.06, 0.06)

while "#FFFFFF" is converted 
to (1.0, 1.0, 1.0)

### To Reproduce

        print(ttk.Colors.hex_to_rgb("#FFF"))
        print(ttk.Colors.hex_to_rgb("#FFFFFF"))

### Expected behavior

(1.0, 1.0, 1.0)
(1.0, 1.0, 1.0)

**Comment by israel-dryer** [comment]
hmmm... strange. I'll have to look into that.  You might be better off using the colorutils module; it  was added later and supports more options and provides output you would normally expected.

```python
>>> colors_to_rgb('#fff', 'hex')
(255, 255, 255)
```
https://ttkbootstrap.readthedocs.io/en/latest/api/colorutils/

**Comment by arthurfait** [comment]
Actually I use Colors.update_hsv, cannot find relevant method in color-utils.
