### ISSUE TITLE
Tableview - insert_row after deleting all rows displays error: Item I001 not found

### ISSUE THREAD

**Issue by antrrax** [israel-dryer/ttkbootstrap#304]
### Desktop (please complete the following information):

ttkbootstrap Version [1.8.0]
OS: [Linux Mint 20.3 Cinnamon X11]

### Describe the bug

insert_row after deleting all rows displays error: Item I001 not found

### To Reproduce

```python
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap.tableview import Tableview

def add_row():
    table.insert_row(END, ('Jimmy', 'Doe', 'jimmy.doe@aol.com'))
    table.load_table_data()

app = ttk.Window()

columns = ['First Name', 'Last Name', 'Email']
data = []

table = Tableview(app, coldata=columns, rowdata=data)
table.pack()

btn = ttk.Button(app, text='Add', command=add_row)
btn.pack()

app.mainloop()
```

With the code above, I follow these steps and the error occurs

1 - Start Tableview with empty lines (I just run the code).
2 - Click the Add button to add a new row.
3 - Select the row and click with the right mouse button, go to the 'Delete selected rows' option and delete all rows.
4 - Click the Add button again, but it displays the error:
_tkinter.TclError: Item I001 not found

**Comment by israel-dryer** [comment]
@antrrax, I think this fixes the issue. However, inspect the change and let me know if it works on your end.

**Comment by antrrax** [comment]
OK here it worked both on linux with python 3.8.10 and on windows using python portable 3.10.5
https://sourceforge.net/projects/portable-python/

Thanks for the quick response.
You can close the topic
