### ISSUE TITLE
messagebox error: AttributeError: 'str' object has no attribute 'invoke'

### ISSUE THREAD

**Issue by antrrax** [israel-dryer/ttkbootstrap#308]
### Desktop (please complete the following information):

ttkbootstrap Version [1.8.0] --> pip3 install ttkbootstrap-master.zip
OS: Linux Mint Cinnamon x64 X11

### Describe the bug

When pressing the Enter button in a message box, it displays error:

> ~/.local/lib/python3.8/site-packages/ttkbootstrap/window.py", line 45, in <lambda>
>     window.bind_class("TButton", "<Key-Return>", lambda event: event.widget.invoke())
> AttributeError: 'str' object has no attribute 'invoke'

### To Reproduce

```python
import tkinter as tk
import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from tkinter import messagebox as msg

root = ttk.Window()

def show_msg():
    msg.showwarning('Warning', 'Test!', parent=root)
    return

b1 = ttk.Button(root, text="Button 1", bootstyle=SUCCESS, command=show_msg)
b1.pack(side=LEFT, padx=5, pady=10)

root.mainloop()
```

Using the code above,
1) Click on the Button 1 button
2) a message will be displayed on the screen
3) I press the "Enter" key (Return) and the error occurs.

### Expected behavior

Pressing Enter should close the message box without displaying an error.

And as soon as you have time, if possible, also 'bind' the <KP_Enter> key in the same event on the <Return> screen for that event

**Comment by israel-dryer** [comment]
The issue was that I was trying to use the `widget` field of the event and that is the Tcl/Tk widget name, and not the actual widget object. So, converting this name using the `nametowidget` method should fix this issue.

**Comment by antrrax** [comment]
I test here.
```
pip3 uninstall ttkbootstrap
pip3 install git+https://github.com/israel-dryer/ttkbootstrap.git@fix_default_enter_button_key_binding
```

Now it no longer displays the error.

The < Key-Return > key: Now no longer displays the error, works correctly

The <KP_Enter> key: No longer displays the error, but does not close the message box

**Comment by antrrax** [comment]
I tested and the <KP_Enter> continues without closing the message box.

**Comment by antrrax** [comment]
I have the impression that you passed the wrong link, because the last link doesn't exist any modification in relation to the previous branch

**Comment by israel-dryer** [comment]
@antrrax, sorry, forgot to push the change to that branch. It should be there now.

**Comment by antrrax** [comment]
Now it's working correctly. Thanks for your quick willingness to fix the issue.
