### ISSUE TITLE
background is visible from padding when using an opaque image that fills the button

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/ttkbootstrap#32]
If I use an image for the button, I can see the default padding around the image. This may not be desirable behavior.

The padding makes the default button size look good. The only way to remove this *post hoc* is to remove the padding in the button constructor when an image is used `padding=0`. From my experience, most of the time that images are used on buttons, they are icons, in which case the extra padding is not noticeable, and probably desirable. So, these default settings might be a reasonable compromise between having to *always* add padding to make the default button size look okay, and *sometimes* having to remove padding when the image completely fills the button (and in the case when I don't want to see the button background coming through).

![image](https://user-images.githubusercontent.com/42584742/115548783-dd251380-a275-11eb-9dc2-447efeac80a5.png)

The result if I remove the padding from default settings. The padding is no longer visible (only the border).  The button doesn't really look that bad. So this is a potential option.

![image](https://user-images.githubusercontent.com/42584742/115549083-3c832380-a276-11eb-85dc-b715d111a367.png)

The result if I remove padding in the button constructor: `padding=0`.

![image](https://user-images.githubusercontent.com/42584742/115549267-70f6df80-a276-11eb-8f05-a1fda7ec1e27.png)

@daniilS, any thoughts on this issue? Have you had any problems with this?

**Comment by daniilS** [comment]
I agree that the most common use for images on buttons would be icons. The only time I've used it myself is in my subclass of the matplotlib toolbar, where the default padding works much better than setting it to 0 in the constructor:
![image](https://user-images.githubusercontent.com/6144189/115552828-a1ee0900-a2a4-11eb-8400-fc46f3ca3494.png)
So I think it works fine as is, as users can always change the padding in the constructor if they do need to.
