### ISSUE TITLE
mac not show menu

### ISSUE THREAD

**Issue by mlb0925** [israel-dryer/ttkbootstrap#352]
### Desktop (please complete the following information):

Mac

### Describe the bug

mac not show menu

### Screenshots

![](http://82.157.62.197:7054/Public/Uploads/2022-09-15/6322918dacaa2.png)

**Comment by mlb0925** [comment]
![](http://82.157.62.197:7054/Public/Uploads/2022-09-15/6322918dacaa2.png)

**Comment by kgall89** [comment]
Hello, I am wondering if there is a solution or workaround to this problem?

Thank you!

**Comment by mlb0925** [comment]
> ello, I am wondering if there is a solution or workaround to this problem?
> 
> Thank you!
> 
> Edit: Found a workaround - External libraries > python3.10>site-packages>ttkbootstrap>themes>standard.py
> 
> Copied an existing theme and added it to the bottom, then changed the # colors to my preferences then called that style in my script like I would a preloaded style
> 
> Hope this helps someone else!
thank you
