### ISSUE TITLE
"." wildcard for Style.configure is no longer working

### ISSUE THREAD

**Issue by mdscientist** [israel-dryer/ttkbootstrap#360]
### Desktop (please complete the following information):

Window 10
Python 3.9

### Describe the bug

 style.configure(' . ', font=('Arial', font_size, 'bold')) throws the error AttributeError: type object 'StyleBuilderTTK' has no attribute ''

if you replace the "." with ".TLabel" or any other custom widget config name it works just fine

**Comment by israel-dryer** [comment]
I'm not able to replicate this issue. What version of ttkbootstrap are you using?
