### ISSUE TITLE
missing emojii support on some Linux distros causing ttkcreator to crash

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/ttkbootstrap#37]
On several linux distributions, there are no pre-installed fonts with emojii support. This causes the **ttkcreator** program to crash because it uses a paintbrush emojii on the color selector button.

The way to fix this is to install a font that supports emojii... `sudo apt-get install fonts-symbola`. However, it's not worth the hassle at this point for such a minor detail. So, I'm removing the emojii from the button until there is a better solution.

![image](https://user-images.githubusercontent.com/42584742/115962309-ae62a380-a4e8-11eb-8ec9-2ee6245b7e0f.png)

**Comment by daniilS** [comment]
A compromise could be to create an image of the icon using the included symbola font, then use that image for the button?

**Comment by israel-dryer** [comment]
@daniilS, that could work. Some time after I originally created this, I packaged the `symbola.ttf` font in order to draw the arrows on the scrollbars. That means I can do the same with the buttons here using `ImageFont` from the PIL package. While it can't be used directly in tkinter, it *can* be used in PIL.

I'm calling the method below every time the screen is updated. So the `selectfg` color on the buttons update as well.

```python
def update_selector_image(self, color=None):
    """
    Draw the selector image using the packaged `Symbola` font.
    """
    font_size = 16
    with importlib.resources.open_binary('ttkbootstrap', 'Symbola.ttf') as font_path:
        fnt = ImageFont.truetype(font_path, font_size)

    im = Image.new('RGBA', (font_size, font_size))
    draw = ImageDraw.Draw(im)
    draw.text((1, 1), "🎨", font=fnt, fill=color or self.getvar('selectfg'))
    self.image = ImageTk.PhotoImage(im)

    try:
        selectors = self.get_selectors()
        if selectors:
            for color in self.style.colors.label_iter():
                selectors[color].children['button'].configure(image=self.image)
    except KeyError:
        # selectors have not been created yet
        pass
```

![image](https://user-images.githubusercontent.com/42584742/115973358-724c3480-a522-11eb-8283-558880dc69e6.png)
