### ISSUE TITLE
ttk. Canvas is invalid when using the background color.

### ISSUE THREAD

**Issue by javen46** [israel-dryer/ttkbootstrap#375]
### Desktop (please complete the following information):

ttk. Canvas is invalid when using the background color.

### Describe the bug

ttk. Canvas is invalid when using the background color.
The code：
ttk.Canvas(self.top, bg=bg, width=screenWidth, height=screenHeight)

**Comment by israel-dryer** [comment]
This is expected behavior as default styles are applied to all widgets.

You can turn off this behavior by adding the argument `autostyle=False` and then you will need to style the widget yourself.
