### ISSUE TITLE
Not forwarding keyword arguments in InfoBox-Dialog

### ISSUE THREAD

**Issue by aDramaQueen** [israel-dryer/ttkbootstrap#398]
### Desktop (please complete the following information):

ttkbootstrap Version: 1.10.0
OS: Windows/Ubuntu/Mint

### Describe the bug

You forgot to forwoard the kwargs in the **Messagebox.show_info(...)** function.

### To Reproduce

```python
root = Window()
text = 'Vvvvvvveeeeeeeeeeerrrrrrrryyyy llloooooonnnnnngggg ttteeeeeexxxxxxttttttttttt'
Messagebox.show_info(text, 'Some title', root, False, width=300)
root.mainloop()
```

### Expected behavior

A Dialog Box with width of 300

### Screenshots

![grafik](https://user-images.githubusercontent.com/52710085/209660754-e45e32c5-1f44-4206-bad2-add613c007cd.png)

**Comment by israel-dryer** [comment]
This is fixed. The thing to note is that the width is in character width. So, 300 would be 300 characters wide.
