### ISSUE TITLE
change themename

### ISSUE THREAD

**Issue by krolaper** [israel-dryer/ttkbootstrap#402]
### Desktop (please complete the following information):

ttkbootstrap 1.10.0
OS Linux

### Describe the bug

I created a window and try to change the subject after changing, but I get a mistake. But then how to change it programmatically?
```
window = ttk.Window(title="AIGod", themename='cosmo', iconphoto=dir + "/bin/image/logo.png", size=[880, 570],
                      resizable=[0, 0])
window.config(themename='lumen')
```
`_tkinter.TclError: unknown option "-themename"`

**Comment by israel-dryer** [comment]
The theme parameter is for convenience and is passed to the style object. To change the theme, you can use the style object directly.

```python
window.style.theme_use("lumen")
```
