### ISSUE TITLE
enter title of bug here

### ISSUE THREAD

**Issue by Arielsva** [israel-dryer/ttkbootstrap#438]
### Desktop (please complete the following information):

Windows 10 Pro

### Describe the bug

Os widgets não são incluídos no Frame em OOP, causando inutilidade do ttk.Frame.

### Screenshots

![image](https://user-images.githubusercontent.com/116596820/223444050-b9d7f6dd-34b8-45c6-bc77-b815e0cac448.png)
![image](https://user-images.githubusercontent.com/116596820/223444176-28a7f18e-d7f5-45a2-a13d-140c84e1dd1f.png)
![image](https://user-images.githubusercontent.com/116596820/223444246-78c56b8e-5203-449e-8e72-fe00ee292af4.png)
![image](https://user-images.githubusercontent.com/116596820/223444414-be128fcb-2be2-42f2-bc95-f759228c1568.png)

**Comment by dmalves** [comment]
Portuguese: "Os widgets não são incluídos no Frame em OOP, causando inutilidade do ttk.Frame."

English: "Widgets are not included in Frame in OOP, causing ttk.Frame to be useless"

----------------

OO approach for a view should:
```python

class View(ttk.Frame):
    ...

```

(English) It is better not to pass frames around. Each view should be a frame on its own. But that is a design decision , it is not you bug. Maybe your bug is that when you press the button, a lambda function is executed and when it finishes all references to View object are lost and it is garbage collected. 


(Portuguese) É melhor não passar os frames para outras classes. Cada view deveria ser um frame sozinho. Mas isso é uma decisão de design, não é seu bug. Talvez o seu bug seja que quando você pressiona o botão, uma função lambda é executada e quando ela termina todas as referências ao objeto View são perdidas e ele é coletado pelo GC.


```python

class View(ttk.Frame):
    ...

class Menu(ttk.Frame):
    def __init__(...):
        self.view= View(master=self)
        
       ttk.Button(
       command = lambda: self.view.grid(...)
      )

```

**Comment by Arielsva** [comment]
Sorry for the last comment being in Portuguese.

The point of passing the frame to other classes is to maintain code organization. Indeed, the block of buttons will be changed to fit within a frame and each view already had a Frame resulting from the App being in a single Window in the project. There is this and several other problems when passing objects between classes, making it mandatory to declare frames and images, for example in main. Appreciate your attention!

**Comment by Arielsva** [comment]
![image](https://user-images.githubusercontent.com/116596820/223676720-cf385c29-667d-4a91-bf2c-8038639d3289.png)
![image](https://user-images.githubusercontent.com/116596820/223676910-79894dd9-d1a3-4f5f-99a5-2dae75c07e56.png)

**Comment by dmalves** [comment]
Consider this example: https://github.com/dmalves/amz_widgets/blob/main/src/amz_widgets/form_entry.py

FormEntry is a ttk.Frame, on the __init__ function master is the parent frame on main window. So you can use FormEntry as any other widget. 

So, looking here https://github.com/Arielsva/GUIProject/blob/main/menu/menu.py  Menu is a container for buttons. Menu could be a frame just like FormEntry.

Now if you need to make Menu appear/disappear, something like a floating frame, consider this example:
https://github.com/dmalves/amz_widgets/blob/main/src/amz_widgets/help_frame.py

I am adapting help_frame from an old code base of mine. Actually, I have a couple  widgets that were coded as little hacks using functions, and now I am changing them to use classes, and making them public. As you can see on the comments it was a function, and now It is a class. But HelpFrame is not a ttk.Frame, as it behaves more like a toplevel. I can decide when it is shown with show method.  

If you want the frame to appear/disappear consider studding HelpFrame. Also, there is an examples on how to use HelpFrame:
https://github.com/dmalves/amz_widgets/blob/main/tests/test_help_frame.py

The code is rather incomplete, but it could help you.

**Comment by Arielsva** [comment]
I thought it was cool, but I don't really see the need to create a class since, as I did, it's enough to export the frame and configure its appearance and disappearance function.
Now, I found it interesting to put this as a function.

**Comment by israel-dryer** [comment]
This doesn't appear to be a bug within ttkbootstrap itself from what I've seen in the comments above; so closing this issue. If you think I'm wrong about this, just let me know. Thanks.
