### ISSUE TITLE
ImageDraw object has no attribute 'rounded_rectangle'

### ISSUE THREAD

**Issue by Olawoledev** [israel-dryer/ttkbootstrap#44]
When i try to run my application using the theme,it gives me an error saying that ImageDraw object has no attribute 'rounded_rectangle'

**Comment by israel-dryer** [comment]
this function was added in pillow version 8.2 and enabled me to start using rounded rectangles to draw better widgets. But, you'll need to make sure your pillow version is at least 8.2 (which I think is the latest version). This should have been done automatically, but if not try running `python -m pip install --upgrade pillow`

https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.rounded_rectangle

**Comment by Olawoledev** [comment]
It worked very fine now after i upgraded the pillow module to the latest version.
