### ISSUE TITLE
How to include theme when using py2exe?

### ISSUE THREAD

**Issue by WilliamNT** [israel-dryer/ttkbootstrap#46]
I am building my application using py2exe, but my software is unusable as it crashed. The reason for that is that the themes.json file (i renamed it to that) is missing... How do I solve this?

**Comment by israel-dryer** [comment]
I haven't used py2exe...I'll have to check.  However, what you'll need to do somehow is tell py2exe to include the package resources. In pyinstaller I've shown how to do that https://github.com/israel-dryer/ttkbootstrap/issues/43, but as I said, I'll have to play aroudn with py2exe to figure out what the convention is for that program.

**Comment by WilliamNT** [comment]
I haven't found out yet to how to do that. If you find anything, please tell me. Also, off topic but do you know any way to use an icon without getting an error (it says it's not defined, tried multiple ways, I'm on windows)

Also for some reason, when testing in Visual Studio Code, the theme is not loaded, but when starting the script manually it's fine.

**Comment by rdbende** [comment]
I never used VS code, but when you run your script from there, it probably changes the working directory, someone had the same [issue](https://github.com/rdbende/Azure-ttk-theme/issues/12) with my theme. The solution is to use an absolute path instead of relative.

**Comment by exec85** [comment]
> I am building my application using py2exe, but my software is unusable as it crashed. The reason for that is that the themes.json file (i renamed it to that) is missing... How do I solve this?

I am also using py2exe since it is much more comfortable when compiling bigger applications. 
I  would also love to see a short step-by-step explanaton for py2exe.
Tried my best to figure out how it could work, but without sucess.
Normally you simpy can add all external files like sound files, images, txt files and so on  pe rdrag-ad-drop after the dist folder was created (after compiling). 
But thats not working for the theme .json file it seems.

**Comment by israel-dryer** [comment]
@WilliamNT, I removed the reliance on Json in the most recent version. I will eventually add back the file reference to a custom theme in a future iteration. However, for now you can import your theme into ttkbootstrap as long as you put it into the required format. There are just a few changes from what you have now I suspect. I've also removed the dependence on the font file, so your package will have no resource setup requirements from ttkbootstrap in 1.0.0+.

https://ttkbootstrap.readthedocs.io/en/latest/themes/themecreator/

**Comment by israel-dryer** [comment]
closing; json dependence has been removed from version 0.5.x and 1.x
