### ISSUE TITLE
Unable to adjust font size

### ISSUE THREAD

**Issue by mdscientist** [israel-dryer/ttkbootstrap#47]
I'm not sure if it's a bug or something on my part, but I can't get this code below to adjust the font and/or size on ttk.Label even when I reconfigure the 'primary.TLabel'.

code:
from tkinter import *
from tkinter import ttk
from ttkbootstrap import Style

root = Tk()
style = Style(theme='journal')
style.configure('primary.TLabel',
     font=('Arial', 25, 'bold')
     )

main_notebook = ttk.Notebook(root)
main_notebook.pack(pady=15,padx=15)
       
master = ttk.Frame(main_notebook)
master.configure(width=300)

cal_Label = ttk.Label(master, text="Choose the starting date.", style='primary.TLabel' )
cal_Label.grid(row = 0, column = 0,sticky=W)

main_notebook.add(master, text='Test')
root.mainloop()

**Comment by israel-dryer** [comment]
Try setting the font directly in the label.

```python
from tkinter import *
from tkinter import ttk
from ttkbootstrap import Style

root = Tk()
style = Style(theme='journal')


main_notebook = ttk.Notebook(root)
main_notebook.pack(pady=15,padx=15)

master = ttk.Frame(main_notebook)
master.configure(width=300)

cal_Label = ttk.Label(
    master, 
    text="Choose the starting date.", 
    style='primary.TLabel',
    font=('Arial', 25, 'bold')
    )
cal_Label.grid(row = 0, column = 0,sticky=W)

main_notebook.add(master, text='Test')
root.mainloop()
```

Here's a working example:
https://replit.com/@IsraelDryer/WhoppingDodgerblueStructures#main.py

**Comment by mdscientist** [comment]
That works, thank you!

For some reason the global style setting ,'style.configure('.', font=('Arial', 18)) with ttkbootstrap, doesn't affect the ttk.Labels like ttk.Style() does.

**Comment by LorenzSLH** [comment]
experienced the same problem. My workaround was to use tkinters label module. Create some instances for fonts you wanna use in your program and then assign it to the labels, buttons, etc.         

```
import tkinter.font as font 
fontTitel = font.Font(family="Helvetica", size=10, weight="bold")
```

With that you have still a global control of all used fonts and dont have to change it in every widget. 

I hope there will be a option in Styles later on to change the font with it. 

best regrads :)

**Comment by israel-dryer** [comment]
Thanks for the input. Agreed this is a good approach.

You can also use the named fonts as well. There are several such as "TkDefaultFont" and "TkTextFont", etc.... These are applied automatically if no font is specifically configured. This is the approach I plan to take eventually, releasing control of the font to the default system to ensure I get the best cross platform look & feel. For now, you'd have to set the font to a named font because I'm currently overriding it, but eventually it will just default (as is normal) to the default font.

To update a default font:
```python
f = font.nametofont("TkDefaultFont")
f.configure(family="Helvetica", size=10, weight="bold")
```
