### ISSUE TITLE
Widgets broken in Pillow 10.0.0

### ISSUE THREAD

**Issue by RSyndergaard** [israel-dryer/ttkbootstrap#472]
### Desktop (please complete the following information):

ttkbootstrap version 1.10.1
Pillow version 10.0.0
OS: Windows 10

### Describe the bug

Bug: Widgets (eg ttkcreator, ttkbootstrap) raise an AttributeError when attempting to start with Pillow 10.0.0 due to constants changes. See release notes: https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#backwards-incompatible-changes

Affected constant is enum PIL.Image.CUBIC, which was changed to PIL.Image.BICUBIC and is not backwards compatible.

### To Reproduce

1. Upgrade Pillow with pip install --upgrade pillow
2. Run widget with python -m ttkbootstrap or python -m ttkcreator

### Expected behavior

AttributeError: module 'PIL,Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

Traceback indicates widgets.py, line 856 in _draw_meter

### Screenshots

![image](https://github.com/israel-dryer/ttkbootstrap/assets/122041570/6fb1a877-45c4-46ee-8c3a-83c89a3c7ee8)

**Comment by jiazhuangle** [comment]
Same question, thanks for the tip. @RSyndergaard
