### ISSUE TITLE
meter example gives error

### ISSUE THREAD

**Issue by beetlegigg** [israel-dryer/ttkbootstrap#474]
### Desktop (please complete the following information):

macOS 11.7.8

### Describe the bug

AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

### To Reproduce

run with the latest pip install of ttkbootstrap

### Expected behavior

No error message and the example runs ok

**Comment by sanjayengineer121** [comment]
### uninstall latest pillow and 


reinstall 
_by using_

**pip install Pillow==9.5.0**
