### ISSUE TITLE
Image zoom error

### ISSUE THREAD

**Issue by xuehangcang** [israel-dryer/ttkbootstrap#475]
### Desktop (please complete the following information):

```python
python -m ttkcreator
```
The following exception occurred during my execution of the above command:
`Mac os m2` Operating System

AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

### Describe the bug

```python
python -m ttkcreator
```
The following exception occurred during my execution of the above command:
`Mac os m2` Operating System

AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?

**Comment by vinzjaystone** [comment]
I encountered the same error, but it's a simple issue to address. All you need to do is replace "CUBIC" with "BICUBIC" on the specified line number in the .py file indicated in the error message.

Hope this helps.
