### ISSUE TITLE
python -m ttkcreator does not work

### ISSUE THREAD

**Issue by handsomepwy** [israel-dryer/ttkbootstrap#478]
### Desktop (please complete the following information):

newest version until 2023/8/10, 1.10.1
Win10
Python 3.10.11 in virtualenv

### Describe the bug

In a virtualenv, I ran python3 -m ttkcreator, and I saw no outcome. So I ran python -m ttkcreator, and there's a bug. 
Then I ran python -m ttkcreator without virtualenv, the GUI appeared normally, but python3 -m ttkcreator still have no outcome. 

### To Reproduce

1. create a virtualenv
2. python3 -m ttkcreator
3. no outcome
4. python -m ttkcreator
5. see error
6. exit the virtualenv
7. python3 -m ttkcreator
8. no outcome
9. python -m ttkcreator
10. normal GUI as expected

### Expected behavior

expect the python3 command to appear GUI, expect python -m  ttkcreator in virtualenv to appear GUI

### Screenshots

![image](https://github.com/israel-dryer/ttkbootstrap/assets/105578000/6d9dc784-5391-4cd6-af8f-0feac42341c7)
![image](https://github.com/israel-dryer/ttkbootstrap/assets/105578000/712f8d7b-b6aa-4dce-9d74-0840861d1f13)
seems that mosaic is useless :)

### Additional context

genius GUI I should say. Btw, why does readthedocs have a Chinese version, quite curious.

**Comment by handsomepwy** [comment]
In virtualenv, PIL version is 10.0.0, the global environment is PIL 9.2.0

**Comment by cool-dev-guy** [comment]
hey @handsomepwy,then you may need to downgrade your PIL version in the `virtualenv`,brobably a value might be changed in the latest PIL version(ie. CUBIC was replaced by BICUBIC)
```shell
# inside venv
pip uninstall Pillow
pip install Pillow==9.2.0
```

**Comment by handsomepwy** [comment]
> 

Well, that does solve the problem. I'm not sure, but I believe changing thw source code of ttkbootstrap shall be more suitable?

**Comment by Intellbg** [comment]
Check if  #490 solved the problem
