### ISSUE TITLE
Symbola font increase .exe file size

### ISSUE THREAD

**Issue by fredcardoso** [israel-dryer/ttkbootstrap#50]
First of all, I would like to congratulate and thank you for the work done with ttkbootstrap. 

Unless I'm mistaken, the Symbola font is most responsible for the increase in file size when converting a script to exe (pyinstaller). Wouldn't it be possible to use another very small font, since very few characters from it are used? 

In my case, when I added the ttkbootstrap library to the project, the file increased by approximately 2.6MB, 2MB being Symbola font.

**Comment by israel-dryer** [comment]
Thanks for the feedback.  Yes, I'm working on another project right now where I'm trying to remove the need for symbola to draw various symbols. I trick is finding a collection of fonts that I can use across various platforms that can be used by the PIL.ImageFont object.  I discovered with testing that `LucidaGrand.ttc` works with PIL.ImageFont on the Mac to produce the checkmark and some other characters. I'll be testing Windows and Linux in the same way.

**Comment by israel-dryer** [comment]
platform specific fonts.... 

- Windows = `seguisym.ttf`  (Windows 7 +)
- Linux = `FreeSerif.ttf`
- Mac OS X = `LucidaGrande.ttc`

These fonts will properly render the symbols I need without the need for importing the `Symbola` font.
