### ISSUE TITLE
No module named importlib.resources

### ISSUE THREAD

**Issue by Trojan-Cipher** [israel-dryer/ttkbootstrap#51]
Hey, I'm new to ttkbootstrap and wanted to start working with it, until i get an error during import.:

_Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import ttkbootstrap
  File "C:\Users\JAMES UCHE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ttkbootstrap\__init__.py", line 29, in <module>
    import importlib.resources
ModuleNotFoundError: No module named 'importlib.resources'_

![err](https://user-images.githubusercontent.com/66879837/131368253-03d07f5f-e345-49f2-964b-3b27266a50b1.PNG)

I've tried, reinstalling ttkbootstrap, importlib, i've tried uninstalling importlib and still get the same error, 'import importlib' still works, but import importlib.resources doesn't, I've also tried upgrading the importlib version with 'pip install --upgrade importlib', still get the same error.

really need help with this, thanks

**Comment by daniilS** [comment]
Have you tried using Python 3.7 or newer?

**Comment by zhengxinonly** [comment]
I using python3.6 get the same error. I switch the version to python3.8 and there is no problem.

**Comment by AsiyaNaqvi** [comment]
How can I solve this issue while still using Python 3.6? As I can't change my python version.

**Comment by daniilS** [comment]
You can install [importlib_resources](https://importlib-resources.readthedocs.io/en/latest/) and manually substitute it for any mention of importlib.resources . I think that should work, but I haven't tested it myself.

**Comment by Trojan-Cipher** [comment]
> Have you tried using Python 3.7 or newer?

not really, but i'll find time to change to python 3.8  very soon, it seems that should work

**Comment by israel-dryer** [comment]
This dependency has been removed in 0.5.2 add in the upcoming 1.0
