### ISSUE TITLE
Add style for readonly widgets

### ISSUE THREAD

**Issue by daniilS** [israel-dryer/ttkbootstrap#53]
Some widgets support the `readonly` state, which currently doesn't look any different from the `default` state. Taking `ttk.Entry` as an example, I'd consider either making it similar to the `disabled` state but with more contrast to keep the text readable, or give it the same style as a `ttk.Label`, with the border only appearing on hover and/or focus.

**Comment by israel-dryer** [comment]
Does it makes sense in practice to have a read-only style?  Readonly simply prevent user input, but doesn't disable the widget...so selection and copy are still possible. In the case of the combobox, it prevents the user from manually entering an option, and restricts the selection to the list of values already provided.  If the intention is to truly disable any interaction, event preventing selection, copy, etc... then the disabled state should be sufficient. Thoughts?

**Comment by daniilS** [comment]
In my specific use case, I use readonly entries as part of a table for cells that shouldn't be editable. The difference from disabled entries is that the contrast makes them a lot less readable (which makes sense for the disabled style). Sticking with Bootstrap styles, I thought [something like this](https://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text) could make sense?

**Comment by israel-dryer** [comment]
I'm currently in the process of adding the state-based "readonly" style. As of now, I think using the `light` color for _light_ themes and the `selectbg` color for _dark_ themes seems to give the best result.

<img width="394" alt="python_cfQlOmSil9" src="https://user-images.githubusercontent.com/42584742/142916199-26a881d8-338b-428f-8a32-bea77d0c71f5.png">

<img width="394" alt="python_bg5ocrsgqD" src="https://user-images.githubusercontent.com/42584742/142916687-e0cb8715-b637-4d28-a360-92429c86ecc7.png">

**Comment by daniilS** [comment]
Looks good to me!

**Comment by israel-dryer** [comment]
@daniilS, [readonly styles have been added](https://ttkbootstrap.readthedocs.io/en/latest/styleguide/entry/#other-entry-styles) for `Entry`, `Spinbox`, and `Combobox`.
