### ISSUE TITLE
Bug(widget.py): Line 856 - Image.CUBIC doesn't exist anymore, should be replaced with Image.Resampling.BICUBIC

### ISSUE THREAD

**Issue by JoshuaBarrass** [israel-dryer/ttkbootstrap#556]
### Desktop (please complete the following information):

Python Version - 3.11.7
ttkbootstrap - 1.10.1
OS - Windows 11

### Describe the bug

On line 856, within _draw_meter - Image.CUBIC isn't a resampling type. 

All available resampling types available : 
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize
https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-filters

Proposed replacement - `Image.Resampling.BICUBIC`

Once change, bug is fixed

### To Reproduce

Attempting to use `Meter` from ttkbootstrap

exact call - 
`
self.progress_meter = Meter(
            self,
            metersize=100,
            padding=5,
            amountused=self.progress_percent,
            metertype="semi",
            subtext="Progress",
            interactive=False,
            textright="%"
        )
`

### Screenshots

![image](https://github.com/israel-dryer/ttkbootstrap/assets/46576310/b078c5d5-cdfd-4c7b-bda2-53a7c942ba3a)

**Comment by rdbende** [comment]
Please stop reporting issues about this error. It's already fixed — though that version is not yet on Pypi.
