### ISSUE TITLE
Provide visual representation of focus on Button

### ISSUE THREAD

**Issue by ikus060** [israel-dryer/ttkbootstrap#56]
As a user using keyboard navigation, I want a way to visually display which widget get a focus.

Using ttkbootstrap, Button doesn't have anything to visually represent the focus. Thus making it hard for the user to know which widget got focus. Would recommend using something visual. Either change colour or adding border, etc.

**Comment by israel-dryer** [comment]
In the meantime, you can manually adjust the style by using something like this:

```python
import tkinter as tk
from tkinter import ttk
from ttkbootstrap import Style


root = tk.Tk()
style = Style()
style.theme_use('flatly')

style.configure('primary.TButton', focuscolor=style.colors.selectfg)

btn = ttk.Button(root, text='Push Me', style='primary.TButton')
btn.pack(padx=10, pady=10)

root.mainloop()

```

![image](https://user-images.githubusercontent.com/42584742/137233426-1ab3f891-1e6d-4775-88c4-76f3f1587650.png)
