### ISSUE TITLE
Provide a Entry Style to identity input that are invalid

### ISSUE THREAD

**Issue by ikus060** [israel-dryer/ttkbootstrap#57]
As a developper, when adding `danger.TEntry` to a widget, I'm expecting the entry to have a particular style with red border similar to bootstrap `<input class="has-error">`.

In Bootstrap, it's possible to set a style to the the `<input>` to make the border red in way to tell the user there is a problem with this fields. I would expect to find something similar in ttkbootstrap. Initially, I was expecting this to be `danger.TEntry`
![image](https://user-images.githubusercontent.com/921251/137231002-a2e67799-8908-49b7-b64d-3c22967cc291.png)

**Comment by israel-dryer** [comment]
@ikus060 I've incorporated this changes into the version 1.0 api that is under development.
https://ttkbootstrap.readthedocs.io/en/latest/styleguide/#entry

![](https://ttkbootstrap.readthedocs.io/en/latest/assets/widget-styles/entries.gif)

**Comment by israel-dryer** [comment]
@ikus060 @daniilS   I am implementing a style for the **invalid** state on entry, combobox, spinbox, and dateentry widgets.

![fCVfd5A6gg](https://user-images.githubusercontent.com/42584742/142972220-475c0a26-ada5-45e4-b463-f8328209c15c.gif)

The user is required to setup the widget validation for the styles to be effective.  You can consult the [ttk documetation](https://tcl.tk/man/tcl8.6/TkCmd/ttk_entry.htm) for details on the **validation**. But, I'll probably add a tutorial in the ttkbootstrap documentation at some point to make it easier to understand for python developers.

Below is the code that creates the example above. I hope to have these changes pushed to GitHub by tomorrow.

```python
import tkinter as tk
import ttkbootstrap as ttk

def validate_number(x) -> bool:
    """Validates that the input is a number"""
    if x.isdigit():
        return True
    elif x == "":
        return True
    else:
        return False

def validate_alpha(x) -> bool:
    """Validates that the input is alpha"""
    if x.isdigit():
        return False
    elif x == "":
        return True
    else:
        return True

# create the toplevel window
root = tk.Tk()
style = ttk.Style()

# register the validation callback
digit_func = root.register(validate_number)
alpha_func = root.register(validate_alpha)

# validate numeric entry
ttk.Label(root, text="Enter a number").pack()
num_entry = ttk.Entry(root, validate="focus", validatecommand=(digit_func, '%P'))
num_entry.pack(padx=10, pady=10, expand=True)

# validate alpha entry
ttk.Label(root, text="Enter a letter").pack()
let_entry = ttk.Entry(root, validate="focus", validatecommand=(alpha_func, '%P'))
let_entry.pack(padx=10, pady=10, expand=True)

root.mainloop()
```

**Comment by ikus060** [comment]
Awesome ! That will be very use full for my application.

**Comment by israel-dryer** [comment]
@ikus060 , I've added a [recipe for this in the cookbook]( https://ttkbootstrap.readthedocs.io/en/latest/cookbook/validate-user-input/).
