### ISSUE TITLE
_tkinter.TclError: unknown option "-bootstyle"

### ISSUE THREAD

**Issue by monkeycc** [israel-dryer/ttkbootstrap#60]
python                              3.8 
ttkbootstrap                      0.5.1

```
\ttkbootstrap\tests\

 python test_button.py

Traceback (most recent call last):
  File "test_button.py", line 52, in <module>
    button_style_frame('', style, 'Solid Button').pack(side=tk.LEFT)
  File "test_button.py", line 21, in button_style_frame
    btn = ttk.Button(
  File "E:\anaconda3\envs\python38\lib\tkinter\ttk.py", line 607, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "E:\anaconda3\envs\python38\lib\tkinter\ttk.py", line 552, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "E:\anaconda3\envs\python38\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: unknown option "-bootstyle"
```

**Comment by Gaoyongxian666** [comment]
我的项目也遇到这个问题了，这个应该是个小BUG，等作者修改吧。

我的解决办法是继承Style类就像作者的demo一样，如果还是不行的话，从GitHub上Clone项目到本地，本地导包的形式。

你也可以参考下我的项目 [CountBoard](https://github.com/Gaoyongxian666/CountBoard)

**Comment by israel-dryer** [comment]
I've been making a lot of changes to this 1.0 version. I'm trying to figure out a good way to inject the bootstyle keywords while also only building styles that I need on-demand to save memory. So, it's been very fluid. If you want something stable, you can [clone the 0.5 branch](https://github.com/israel-dryer/ttkbootstrap/tree/0.5). However, I pushed a ton of changes just now that I think will fix this issue.  Let me know if you still have this error.

With this new update, you can no longer subclass Style, as it is a singleton. Style is now a method that returns an instance.

Also, if you set the theme initially with Style("darkly") or something like that... things are looking fine. However I have a [bug now that cause some styles to not update ](https://github.com/israel-dryer/ttkbootstrap/issues/62)when you use the `theme_use` method after style has already been created.

**Comment by Gaoyongxian666** [comment]
Support author, thank you for development

**Comment by israel-dryer** [comment]
another thing.... the imports are different because I'm overriding the widgets. I've tried to simplify it.

```python
import tkinter as tk
import ttkbootstrap as ttk

root = tk.Tk()
style =ttk.Style("superhero")

btn = ttk.Button(root, text="Push Me")
btn.pack()

root.mainloop()
```

**Comment by hturkcan** [comment]
hello.
```
import tkinter as tk
import ttkbootstrap as ttk

root = tk.Tk()
style =ttk.Style("superhero")

btn = ttk.Button(root, text="Push Me")
btn.pack()

root.mainloop()
```
This usage gives me an error.
AttributeError: module 'ttkbootstrap' has no attribute 'Button'

**Comment by israel-dryer** [comment]
@hturkcan Version 1.0 is not published to PyPI yet as it's not 100% complete, so you'll need to install using the following:
```shell
python -m pip install git+https://github.com/israel-dryer/ttkbootstrap
```

<img width="311" alt="image" src="https://user-images.githubusercontent.com/42584742/143074633-9ddf8d93-6241-4081-bc55-cde2db4820d9.png">
