### ISSUE TITLE
Add High DPI support

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/ttkbootstrap#78]
Try to find a way to support High DPI awareness  out-of-the-box. The easiest way might be some kind of parameter added to the `Tk` widget that enables certain OS specific settings and possibly calculates the appropriate scaling by default while allowing for overides.

# Without High DPI Awareness
The application is running on Windows 11 _without_ high DPI awareness

- images and fonts are noticeably pixelated on a 4k screen, not quite so noticeable on 2k
- relative scaling of widgets appears ok

![image](https://user-images.githubusercontent.com/42584742/143487904-2d30941a-77c4-4b20-9d8c-dd5c9c85652a.png)

# High DPI Awareness Enabled (No Tk Scaling)

The exhibit below illustrates the application on Windows 11 with DPI awareness turned _on_ 

* image-based layouts are too small as they are not scaled appropriately
* fonts are not consistently scaled, too big in some cases, too small in others

```python
from ctypes import windll
windll.shcore.SetProcessDpiAwareness(1)
```

![image](https://user-images.githubusercontent.com/42584742/143487650-73cac329-539e-462f-814d-2166b5c9f902.png)

# High DPI Awareness Enabled (Tk Scaling = 1.5)

The exhibit below illustrates the application on Windows 11 with DPI awareness turned _on_ and additional scaling settings configured using tkinter.

* the widgets and fonts all appear crisp and scaled correctly
* the application window size is noticeably smaller
* the titlebar looks a bit too big relative to the window size

```python
from ctypes import windll
windll.shcore.SetProcessDpiAwareness(1)

# after creating root
root.tk.call('tk', 'scaling', 1.5)
```

<img alt="python_pQkYLY149M" src="https://user-images.githubusercontent.com/42584742/143489451-3f636784-d082-49fc-9be4-db2b0f34cad0.png">

**Comment by daniilS** [comment]
Leaving a comment here to remind myself to respond properly in a few days - I've done a lot of playing around with tk scaling on Windows so will need to remember what exactly I'd found. 

To scale the titlebar appropriately, I think one of the options of SetThreadDipAwareness (rather than Process) did the trick. However, I found that almost all of the options had some issues with them when a window is created on one monitor, and then dragged to another monitor with a different DPI (the joys of using a laptop + an external monitor). I ended up settling for DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED as a compromise myself.

**Comment by israel-dryer** [comment]
apparently, both of these have the same effect. Not sure what the difference is, other than one appears to be a convenience method and the other appears to be a property setter.

```python
from ctypes import windll

windll.user32.SetProcessDPIAware()
windll.shcore.SetProcessDpiAwareness(1)
```

**Comment by israel-dryer** [comment]
I may have a relatively simple fix for this. 

I discovered that one important step is to enable DPI awareness **before** tkinter is started up because the internal tkinter scaling is set when the `Tk` object is instantiated.

I think the best way to handle the images is to simply adjust the size of the image. I originally designed the images with a display that had a scaling of 1.33, so this is my baseline.

```python
root = tk.Tk()
scaling = root.tk.call('tk', 'scaling')
```
new size = high-dpi scaling / baseline scaling * original size

I've created a helper method that does these calculations automatically. And because I'm already building the images at a much larger size and then sizing down, calculating the new final size is a simple fix.

Below are the checkbutton at full 4k high-dpi. 

<img alt="python_8XD3Egp6jF" src="https://user-images.githubusercontent.com/42584742/143511365-792d31ea-631e-40b3-96db-48a0a35c2462.png">

I need to work on the scaling on the fonts, but the images I think will work out just fine.

Finally, I'll need to test this on Linux and eventually Mac. High DPI is a display configuration settings in Linux as far as I know. So, I'm thinking that the ttk widget scaling will happen automatically on Linux because of how I'm calculating the image sizes on demand.

**Comment by israel-dryer** [comment]
I've added a function to enable high dpi for Windows and Linux.
```python
import tkinter as tk
from ttkbootstrap.style import utility

# window (create BEFORE root)
utility.enable_high_dpi_awareness()

# linux (create AFTER root)
root = tk.Tk()
utility.enable_high_dpi_awareness(root=root, scaling=2.0)
```

<img alt="image" src="https://user-images.githubusercontent.com/42584742/143669262-2cd10d27-f26c-4eba-8aea-51fa724d4af0.png">

**Comment by israel-dryer** [comment]
while documenting the library, I realized I needed to flatten the modules, and that let me to refactoring several items. The only thing that really changes from an api perspective was the utility module, which is now in the root.

So, this method is now in `ttkbootrap.utility.enable_high_dpi_awareness`
