### ISSUE TITLE
Change Meter style

### ISSUE THREAD

**Issue by Andermutu** [israel-dryer/ttkbootstrap#79]
Hi!

I am trying to change meterstyle during my program runtime:

```
mymeter.amountused = 4
mymeter.meterstyle = 'danger.TLabel' 

//or 

mymeter.configure(meterstyle = 'danger.TLabel')

```
That is what I have tried so far, but does not work, so I wonder if there is an option to change the meterstyle once has been created.

Thanks in advance!

**Comment by israel-dryer** [comment]
Are you using the 0.5 or 1.0 version?

In 1.0 you can change it using the new keywords api, but I don't think I added a runtime configuration in 0.5.

**Comment by Andermutu** [comment]
> Are you using the 0.5 or 1.0 version?
> 
> In 1.0 you can change it using the new keywords api, but I don't think I added a runtime configuration in 0.5.

Hi!

I was using the 0.5 version, and updating to 1.0 solved the problem. I use `mymeter.configure(bootstyle='info')` to change meter style.

Thank you.

**Comment by Ginias2000** [comment]
how can i change the Meter bg_color by defaut it taking the root style bg but i want its bg to be diferent i used every method online but it not working
