### ISSUE TITLE
Can text widgets add an attribute textvariable?

### ISSUE THREAD

**Issue by Gaoyongxian666** [israel-dryer/ttkbootstrap#87]
tk.Text()

This is not necessary.

**Comment by israel-dryer** [comment]
@Gaoyongxian666 , no as far as I know, this widget does not accept a text variable.
https://tcl.tk/man/tcl8.6/TkCmd/text.htm

**Comment by Gaoyongxian666** [comment]
yes，I saw that it doesn't have this attribute.

I want to encapsulate a class for easy use,just like entry

**Comment by israel-dryer** [comment]
It really depends on what you are trying to achieve.

Are you looking for multi line read only? If so, you can actually do
multiple lines on a label widget.

The text widget is a very powerful and complex widget with a lot of
tagging, indexing, and formatting features. I think that is probably why
there is no variable, it would interfere with that functionality.
