### ISSUE TITLE
Link to repl.it broken in docs?

### ISSUE THREAD

**Issue by JordanDworaczyk** [israel-dryer/ttkbootstrap#89]
Great looking project. I was reading through the documentation and found a link on this page [here](https://ttkbootstrap.readthedocs.io/en/latest/gallery/calculator/#style-summary). I'm referring to the link seen in the picture. The link: `Run this code live`. 

![image](https://user-images.githubusercontent.com/19294959/145501238-ceef8f8d-5480-4ff2-999f-6f3bdc999e15.png)

When I click on this link it doesn't take me anywhere.

Anyways, nothing serious. Just wanted to give you guys a heads up in case it is a broken link. Cheers.

**Comment by israel-dryer** [comment]
The repl.it links have all been updated.
The collection of examples can also be found here: https://replit.com/repls/folder/ttkbootstrap-gallery
