### ISSUE TITLE
scrollbar becomes a ▯

### ISSUE THREAD

**Issue by whmsft** [israel-dryer/ttkbootstrap#93]
The screenshot:
![cap](https://user-images.githubusercontent.com/72214351/146675369-4386fb08-8082-4754-a531-e07b45da13b3.JPG)

**Comment by israel-dryer** [comment]
To help figure this out:

- What OS version are you running? 

- Can you post an example of the code you used to build the scrollbar?

**Comment by daniilS** [comment]
I've noticed the same issue when I had someone run a script I wrote using ttkbootstrap on macOS Big Sur, for reference.

**Comment by israel-dryer** [comment]
@daniilS, was this something that happened with 0.5, or did you just notice it on 1.0?

**Comment by daniilS** [comment]
This was on 0.5

**Comment by israel-dryer** [comment]
Ok, this is a 0.5 issue.

The problem is that I'm using "alt" theme as the base when creating the elements for that widget, and that theme does not exist on Mac. This must have always been a problem and I just didn't notice.

I recently got a Mac mini to run tests on Mac; previously I didn't have that option. 

1.0 looks good on Mac in my latest tests.

**Comment by daniilS** [comment]
In 0.5 the arrows are created using "🞁" characters and similar, so I think the issue is the LucidaGrande.ttc font missing those glyphs on (some versions of) macOS. 1.0 doesn't use those characters any more, so that must be what fixed it.

**Comment by israel-dryer** [comment]
Strangely, the character is off in the actual code file; it must have gotten corrupted in one of the updates:

![Screen Shot 2021-12-19 at 6 38 21 PM](https://user-images.githubusercontent.com/42584742/146695160-52abd749-5097-4d32-a663-c317e36f74c9.png)

However, this isn't the only problem. From everything that I could find, LucidaGrande.ttc should be available on nearly all versions of MacOS that are running today. For whatever reason, even when I updated the characters, it still would not display the **left** and **up** triangles correctly. So, I decided to use the "Apple Symbols.ttf" font, which should be available on any Mac OS dating back to 2003.

Below are screenshots of v0.5. I'll need to change the default font in 1.0 as well in the cases where I'm using a font to draw images, just in case.

![Screen Shot 2021-12-19 at 6 38 21 PM](https://user-images.githubusercontent.com/42584742/146696233-213a3016-61f0-4cd4-94ca-54fa5fc25bc3.png)

![Screen Shot 2021-12-19 at 7 19 34 PM](https://user-images.githubusercontent.com/42584742/146696259-b83b97d9-9b98-4121-88dc-06728d599b1d.png)

**Comment by whmsft** [comment]
> To help figure this out:
> 
> * What OS version are you running?
> * Can you post an example of the code you used to build the scrollbar?

OS: Windows 7 (lol)
The program is just the ttkcreator
And I used v0.5 (PyPi latest)

**Comment by israel-dryer** [comment]
@whmsft, ok, the corrupted unicode characters would have affected Windows as well. So, as soon as I push that update, I'll let you know.

**Comment by daniilS** [comment]
@israel-dryer very strange - I checked the files on pypi and the characters show up fine for me. [What code point](https://www.babelstone.co.uk/Unicode/whatisit.html) are they showing up as in your file?

**Comment by israel-dryer** [comment]
@daniilS the medium triangles I'm using won't show up on Mac OS...even in the editor. They look fine on Windows & Linux.. this whole thing has me confused, lol. I thought it was something wrong with the file, but when I look at the source in GitHub, it looks fine. 

These are the original characters... 🞁, 🞃, 🞀, 🞂

**Comment by daniilS** [comment]
@israel-dryer okay, that's very strange. I don't have a mac to test it on sadly, but could you see if replacing the upwards triangle with "\U0001F781" still has the same result, to see if the issue is with the encoding of the file or with unicode in general?

**Comment by israel-dryer** [comment]
@daniilS, @whmsft, I think I'm going to save myself the trouble and just using the 'default' theme scrollbar arrows, and set the color as the theme 'fg' color.
<img width="120" alt="image" src="https://user-images.githubusercontent.com/42584742/146699528-5f3172d6-9569-47c2-861c-82a3d2b24c31.png">

**Comment by daniilS** [comment]
That might be the easiest solution. Having taken a look at LucidaGrande.ttc, it looks like it doesn't contain any 32-bit unicode characters at all - and even in the 16-bit region, it's missing a lot of glyphs:
![image](https://user-images.githubusercontent.com/6144189/146700523-219637ce-57f0-4433-b8d8-8fb6b2c554c8.png)

In case you want to use triangle glyphs for anything in the future, the 16-bit triangles are present in Apple Symbols.ttf, and I would hope also in Windows 7:
![image](https://user-images.githubusercontent.com/6144189/146700858-b02e8179-b3c9-47fc-ab3e-87175adf3e1c.png)

**Comment by israel-dryer** [comment]
Thanks, that's helpful

**Comment by israel-dryer** [comment]
@whmsft, try installing again and letting me know how it goes:
```python
python -m pip install ttkbootstrap==0.5.3
```

**Comment by whmsft** [comment]
Yeah! Now it works great
